### ISSUE TITLE
关于foxone使用手机验证码打开红包链接的问题报告

### ISSUE THREAD

**Issue by antone0411** [fox-one/bugs-hunter#1]
**描述错误**
打开群友的foxone红包链接需要手机验证码登录，手机号随便输入了几位数字，可以点击“发送验证码”

**重现**
重现行为的步骤：
1.转到“ 手机验证码登录页面”
2.随意输入几位数字
3.点击发送验证码
4.看到错误，跳转界面，直接发送

**预期行为**
手机号不满11位应提示输入错误

**截图**

![image](https://user-images.githubusercontent.com/38535962/68296315-4a1f0a80-00cf-11ea-81fa-a182d99b15ae.png)

**Comment by xuyan1214** [comment]
我们是国际化业务，手机号位数，不同国家可能不一样。如果要实现不同国家的手机号识别，实现成本太高，所以暂不解决。

另外，提交 issue 时记得附上自己的邀请码，以便价值 issue 提交成功后发放奖励。
