### ISSUE TITLE
在fox app隐藏fmc1会导致收不到空投

### ISSUE THREAD

**Issue by evo-lee** [fox-one/bugs-hunter#10]
版本:IOS 测试 2.7.0
手机：iPhone XR  13.1.3
邀请码：D655KR

不知道是不是bug的内容：
Fmc1本来放f1ex交易所的，8号转的foxapp,然后就顺手隐藏了。在mixn上隐藏资产是可以被读取到的，就没放心上。今天一看，好几天的收益都没有，看来是不能读取了，有点坑。

![EF7F4FA7-86D6-4B3A-A082-7CACA16565DE](https://user-images.githubusercontent.com/34160928/68723776-98af3600-05f4-11ea-8275-7c8a1a0ac1e9.jpeg)

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xuyan1214** [comment]
您好，可否在 mixin 上发一下手机号码给我，方便技术查证。我的 mixin id 是37160854，发条@fox.one

**Comment by evo-lee** [comment]
最新补充：我8号把fmc1转出f1ex交易所，然后13号一看空投全在f1ex交易所这， app未识别到，这算是个bug吧。

**Comment by xuyan1214** [comment]
问题已解决，奖励会在 3 个工作日内发放！感谢支持
