### ISSUE TITLE
新人进入易上手操作指引

### ISSUE THREAD

**Issue by doujingling** [fox-one/bugs-hunter#100]
B.Watch DEX 我操作了十分钟搞不定，没有交易成功。

希望交易软件简单方便，易上手。
有交易 动图 指引更好。

**
  - 操作系统：安卓系统
  - 浏览器 Mixin 0.18.10
  - 版本 0.18.10
  - 设备：魅族5
  - 操作系统：安卓系统
  - 版本  8.0.0.0A
  - 手机系统语言 [中文]
  - Fox.ONE 版
  - Mixin邀请码  PBKJ

**其他内容**
希望世界各地的新人都交割容易上手。

**Comment by riririridiculous** [comment]
感谢您的建议，不过建议希望尽量具体。后续我们会考虑加一些文档或者引导。给您赠送 10 FC 积分，奖励会在一周内到账。
