### ISSUE TITLE
fox-one客户端数据分析全屏显示有问题

### ISSUE THREAD

**Issue by zqkyo** [fox-one/bugs-hunter#101]
**错误**
客户端交易对数据分析全屏显示有问题，不论怎么设置显示折线图、BOLL等，切换全屏后，依然按照默认设置的图来显示，无法全屏显示调整后分析图。
已向经理反馈，他让我来提交bug。

**重现**
重现行为的步骤：
1.转到“任意交易对”
2.点击“ 图表设置.”
3.将显示设置调整为非默认选择项
4.看到缩略图已经调整过来
5.单击缩略图进入全屏显示
6.发现仍未调整（出现错误）

**预期行为**
全屏数据分析与缩略屏数据分析保持一致，或在全屏显示里增加显示设置以调整全屏显示图。
![微信图片_20200203013040](https://user-images.githubusercontent.com/56794875/73612259-2d8a6400-4625-11ea-8d35-b09c4c8dfcdc.jpg)
![微信图片_20200203013055](https://user-images.githubusercontent.com/56794875/73612263-35e29f00-4625-11ea-93be-aa340378770c.jpg)

设备： 小米MIX3
操作系统：安卓10      MIUI11.0.1稳定版
Fox.ONE 邀请码：5GP7M8

**Comment by riririridiculous** [comment]
这个横屏的页面是可以竖直滚动的，MACD 和 Volume 的副图表已统一展示。谢谢反馈！奖励将在 1 周内发放。
