### ISSUE TITLE
[FoxONE]邀请好友页面文字显示问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#102]
**描述错误**
邀请好友页面上的文字部分重叠了

**重现**
重现行为的步骤：
1.转到“ 钱包”
2.点击“ 邀请好友“
3.看到错误：页面上方的“邀请好友”四个字与下一行的邀请说明文字部分重叠了

**预期行为**
预期看到无重叠的文字

**截图**
![截图1](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gbkayokfrvj30ku112173.jpg)
页面上方的文字部分重叠

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- Fox.ONE 版本 [2.10.0 (374)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
使用的是TESTFLIGHT内测版本

**Comment by riririridiculous** [comment]
谢谢反馈，奖励将于 1 周内发放。

**Comment by moubuns** [comment]
fix
