### ISSUE TITLE
[bwatch dex]网页端BOXBTC交易对图表的“前往到”操作问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#103]
**描述错误**
在网页端的BOXBTC交易对的图表下点击“前往到”按钮，选好时间后，点击箭头无法前往，弹出框不会消失。

**重现**
重现行为的步骤：
1.转到“ 主页
2.点击“ BOXBTC交易对”
3.点击“ 前往到 ”， 看到弹出框
4.选择时间：2020.02.03 11:04
5.点击右箭头
6.看到错误：弹出框没有消失
7.再次点击右箭头
8.看到错误：弹出框依然在

**预期行为**
6 弹出框消失，并且前往指定日期

**截图**
![第6步](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gbkcelngigj30ls0gbdgf.jpg)
第5.6步：点击右箭头弹框不会消失

**环境信息（请填写以下信息）：**

- 浏览器：[Google Chrome 版本 79.0.3945.130（正式版本） （64 位）]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
无

**Comment by riririridiculous** [comment]
根据步骤，没办法重现，点击右箭头后弹框会消失，一切正常。可直接联系我们 Mixin ID: 37066011，进一步确认问题。感谢支持！
