### ISSUE TITLE
[bwatch dex]网页端交易对图表的“前往到”日历文案问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#104]
**描述错误**
在网页端的交易对的图表下点击“前往到”按钮，弹出来的日历文案把“星期三”显示成“我们”

**重现**
重现行为的步骤：
1.转到“ 主页“
2.点击“ BOXBTC交易对”
3.点击“ 前往到 ”
4.看到错误：弹出的日历文案显示”我们“，（PS：除了周三错误表述成我们，还存在不统一的表述，有星期一也有周二）

**预期行为**
第4步 看到正确的星期表述：星期三

**截图**
![第4步](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gbkcelm0b8j30mq0h7gm8.jpg)
第4步弹出的日历文案显示“我们”

**环境信息（请填写以下信息）：**

- 浏览器：[Google Chrome 版本 79.0.3945.130（正式版本） （64 位）]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
无

**Comment by riririridiculous** [comment]
谢谢反馈，该问题是由于接入了 tradingview。奖励将于 1 周内发放。
