### ISSUE TITLE
[FoxONE]小程序签到与活动页面显示问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#105]
**描述错误**
任务页面和交易积分详情页面图标和文字没有对齐

**重现**
重现行为的步骤：
1.转到“ 发现“
2.点击“ 小程序”
3.点击“ 签到与活动”
4.看到错误：特邀任务和日常任务下的各项图标和文字没有对齐。
5.点击“交易积分天天领”右侧的“查看奖励”
6.看到错误：每一项的图标和文字均没有对齐。

**预期行为**
4.6步看到图标和文字对齐

**截图**
![第4步](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gbkg15ykynj30ku112n9f.jpg)
第4步：特邀任务和日常任务下的子项图标和文字没有对齐

![第6步](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gbkg16zehbj30ku112n73.jpg)
第6步 交易积分天天领的每一个领取记录的图标和文字均没有对齐

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- Fox.ONE 版本 [2.10.0 (374)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
使用的是TESTFLIGHT内测版本

**Comment by riririridiculous** [comment]
交易领奖对齐我这里不能重现，需待确认，谢谢反馈。

**Comment by riririridiculous** [comment]
请升级到最新版本体验，谢谢支持！
