### ISSUE TITLE
[FoxONE]安卓设备扫描收款码相关问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#106]
**描述错误**
安卓设备扫描设定收款金额的收款码后付款页面没有自动填充金额

**重现**
重现行为的步骤：
1.转到“ 钱包“
2.点击“ 扫码和支付”
3.使用另一设备(ios) 生成收款金额为0.01USDT的二维码
4.本安卓设备扫描该二维码
5.看到错误：付款页面的金额栏为空
6.使用安卓设备生成收款金额为0.01USDT的二维码，ios设备扫描后付款页面自动填充0.01

**预期行为**
4步看到金额栏自动填好0.01

**截图**
![第3步](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gbkg17xku0j30ku112du3.jpg)
第3步：ios设备生成的收款二维码

![第4步](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gbkg2wojgdj30u01t07gk.jpg)
第5步：安卓设备扫描后付款页面的金额为空（对方头像也出不来）

![第6步](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gbkg2gdwzzj30u01t0k8t.jpg)
第6步 安卓设备生成的收款二维码

![第6步](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gbkg2xscwyj30ku1127it.jpg)
第6步：ios设备扫描后付款页面自动填充0.01

**环境信息（请填写以下信息）：**

- 操作系统：[ 安卓 9]
- 设备：[ 华为荣耀8x]
- 操作系统：[EMU 9.1.0]
- Fox.ONE 版本 [2.10.0 (208)]

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- Fox.ONE 版本 [2.10.0 (374)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
ios使用的是TESTFLIGHT内测版本

**Comment by riririridiculous** [comment]
谢谢反馈，奖励将于 1 周发放。

**Comment by zhdhr0000** [comment]
2.11.1版本会修复这个问题
