### ISSUE TITLE
[bwatch dex]亮色主题下资产详情页关闭按钮缺失

### ISSUE THREAD

**Issue by minkooz** [fox-one/bugs-hunter#108]
**描述错误**
亮色主题下资产详情页看不到退出当前页面按钮（点空白处仍然可退出），另外，在暗色模式下可见白的退出按钮，怀疑是都用了白色导致不可见。

**重现**
重现行为的步骤：
1.在主页面点击“资产”标签
2.点击“MIXIN MESSENGER”或“Fox.ONE”项目的资产
3.看到错误

**预期行为**
左上角应有关闭按钮，实际没有。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息：**
  - 操作系统：iOS 13.3.1
  - Mixin内置
  - 版本 提交当日版本
  - 设备：iPhone 11
  - 手机系统语言 中文
  - Fox.ONE 邀请码 Y3PWY3

**Comment by riririridiculous** [comment]
问题已确认。谢谢反馈，感谢支持！奖励将于 1 周内发放

**Comment by divisey** [comment]
fixed
