### ISSUE TITLE
[小钱包]转账记录重复问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#109]
**描述错误**
转账记录每隔大概10个记录就会出现一个重复的记录

**重现**
重现行为的步骤：
1.在 mixin 畅聊版对话框点击小钱包机器人图标 
2.点击“ BOX”
3.下滑查看转账记录
4.看到错误：两笔金额相同的BOX转账记录 -3.5 BOX
5.分别点击两条转账记录
6.看到交易编号一样
7.返回上一级，继续下滑
8.看到错误：两笔金额相同的BOX转账记录 +0.01373627 BOX
9.分别点击两条转账记录
10.看到交易编号一样

**预期行为**
第4步看到一条金额为-3.5BOX的转账记录
第8步看到一条金额为+0.01373627的转账记录

**截图**
![截图1](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gbnt65eg79j30ku112tib.jpg)
第4步两笔金额相同的BOX转账记录 -3.5 BOX

![截图2](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gbnt648ymbj30ku112wqy.jpg)
-3.5 BOX 交易详情

![截图3](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gbnt66epr6j30ku112qcp.jpg)
第8步两笔金额相同的BOX转账记录 +0.01373627 BOX

![截图4](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gbnt67zlbuj30ku112wr6.jpg)
+0.01373627 BOX 交易详情

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- mixin 畅聊版 版本 [0.18.5（264） ]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**

无

**Comment by divisey** [comment]
fixed
