### ISSUE TITLE
USDT买不了

### ISSUE THREAD

**Issue by doujingling** [fox-one/bugs-hunter#110]
我在Exinone上面买的USDT不可以兑换box.
在ATM上可以兑换box.
![S00207-18002220(1)](https://user-images.githubusercontent.com/48606479/74028648-d64e1000-49e5-11ea-86bc-a381b6fef73b.jpg)
![S00207-18170907](https://user-images.githubusercontent.com/48606479/74028664-de0db480-49e5-11ea-9671-3e683ead7314.jpg)

**环境信息（请填写以下信息）：**
  - 操作系统：安卓
  - 浏览器  https://dex.firesbox.com
  - 版本 mixin0.19.4
  - 设备：魅族5
  - 操作系统：安卓
  - 版本 8.0.0.0A
  - 手机系统语言 [中文]
  - mixin 邀请码 PBKJ

**Comment by yiplee** [comment]
在 EXIN 上买的 USDT 是 omini 比特币版本的，交易 BOX 需要以太坊 erc20 版本的 USDT，不是一个版本。
你可以去 exin 的工具箱兑换成 erc20 版本的 USDT

**Comment by doujingling** [comment]
USDT对换过了，也买到box了。总之一句话:交易繁琐，比装大象步骤还多。
![S00208-20160723](https://user-images.githubusercontent.com/48606479/74085096-92740d00-4ab0-11ea-9978-040294f40db7.jpg)
希望box在图片内一次完成交割。

**Comment by riririridiculous** [comment]
您也可以选择在 ZOTC 直接购买 ERC20 版本的 USDT 后，用 ATM 兑换 BOX，或者用氢定投去买 BOX，就能省去兑换的麻烦了哈 😊
