### ISSUE TITLE
FoxONE 安卓 APP，底栏跳转、FC 显示、会员数据显示

### ISSUE THREAD

**Issue by nixding** [fox-one/bugs-hunter#111]
**描述错误**

bug1. 底栏的「FOX」「发现」「钱包」，点击时不能实现对应跳转
bug2. FC 数量显示为0，实际上并不为0（在「钱包」页面下，未点击进入下一级）
bug3. 数据中的会员指数，查看时不能进入而是弹窗，显示「成为 FoxONE 会员」

**bug1重现**

一般发生在进入小程序「签到与活动」并关闭后，更具体地：

- 并不是完全不跳转，在左侧的「FOX」「发现」以及右侧「发现」「钱包」这两组相邻路由间跳转不能实现，但是，「FOX」「钱包」这两个不相邻之间可以跳转

**bug2重现**

一直存在

**bug3重现**

一直存在

**预期行为**

bug1. 进入对应的页面
bug2. 显示正确的 FC 数目
bug3. 进入指数的详情页

**环境信息（请填写以下信息）：**

  - 操作系统：安卓7.1.2
  - 设备：坚果3
  - 操作系统：SmartisanOS v6.7.3
  - 手机系统语言：中文
  - Fox.ONE 版本：2.10.0 (208)
  - Fox.ONE 邀请码：Y3PWXZ

**其他内容**

- 是会员，通过购买，而不是 FC 兑换
- 尝试过清除缓存，没有解决

**Comment by riririridiculous** [comment]
问题已确认，奖励会在 7 个工作日内发放。谢谢支持😊

**Comment by zhdhr0000** [comment]
之前版本会员信息均为正数，之后线上将会员信息修改为小数，导致获取会员信息报错，新版本将会修复
