### ISSUE TITLE
标题：[bwatch dex]网页端交易对的法币价格显示异常 

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#112]
**描述错误**
在网页端的交易对下显示的法币价格异常。

**重现**
重现行为的步骤：
1.转到“ 主页
2.点击“ BTC/USDT交易对”
3.看到错误：9800.00 ~（约等于）$1399.68
4.点击“ BOX/USDT交易对”
5.看到错误：1.9630 ~（约等于）$0.28
6.EOS/USDT交易对同错误

**预期行为**
第3步看到 $9800左右的数字，而不是1399.68
第5步看到1.96左右的数字，而不是0.28

**截图**
![第3步](https://wx3.sinaimg.cn/mw690/007nqC8Ygy1gbqeb0ux3dj30tz0g5ta3.jpg)

![第5步](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gbqeb1ffytj30u10erabw.jpg)

**环境信息（请填写以下信息）：**

- 浏览器：[Google Chrome 版本 79.0.3945.130（正式版本） （64 位）]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
无

**Comment by divisey** [comment]
fixed
