### ISSUE TITLE
[小钱包]设置币种开关的标题显示错误

### ISSUE THREAD

**Issue by Halimao** [fox-one/bugs-hunter#113]
**描述错误**
设置货币单位开关的标题显示为“设置涨跌颜色”

**重现**
重现行为的步骤：
1.在 mixin 对话框点击小钱包机器人图标 
2.点击“ 齿轮图标”
3.点击“货币单位”一行右侧的齿轮图标
4.看到错误：设置涨跌颜色

**预期行为**
看到类似“设置货币单位”的描述

**截图**
![截图1](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gbrlsy25ysj30u01t0gqy.jpg)
错误的文字见划线

**环境信息（请填写以下信息）：**

- 操作系统：[ 安卓 9]
- 设备：[ 华为荣耀8x]
- 操作系统：[EMU 9.1.0]
- mixin 版本 [0.19.0]
- Fox.ONE 邀请码 [Z6WGNY]

**Comment by divisey** [comment]
fixed
