### ISSUE TITLE
[FoxONE app]氢定投创建定投计划的页面显示问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#115]
**描述错误**
氢定投添加定投计划时，页面缩小到了一个小方块，造成操作困难。

**重现**
重现行为的步骤：
1.转到“ 发现
2.点击“ 小程序”
3.点击“ 氢定投 ”
4.点击右下角“ + ”
5.点击“ETF”
6.看到错误：币种选择框上移覆盖了ETF输入框； 页面下半部分空了。
7.点击“BTC”
8.看到错误：表单无法在页面全部显示出来。

**预期行为**
第6步 币种选择框在ETF输入框下方
第8步 表单在页面全部显示出来

**截图**
![第6步](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gby9p6nit6j30ku112gpc.jpg)
第6步看到的错误

![第7步](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gby9p5njgxj30ku1120ya.jpg)
第7步执行完的样子

![第8步](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gby9p7h2k4j30ku112wmq.jpg)
第8步看到的错误

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- Fox.ONE 版本 [2.10.0 (374)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
无

**Comment by cg-xuy** [comment]
问题已修复，新版本上线即可解决，奖励将会在3个工作日内发放，谢谢支持！
