### ISSUE TITLE
关于注册时邀请码，OTC实名认证位置及OTC需要具备BTC功能的建议

### ISSUE THREAD

**Issue by Jenny0523** [fox-one/bugs-hunter#116]
1，用户在下载FOXONE  APP后，要求填写 邀请码。

但填写完之后 在钱包那里还要重新绑定，非常麻烦 

2，OTC的实名认证入口找不到，非常不显眼

3，因为进践行群需要购买BTC,建议增加购买BTC的功能 。

我的FOXONE 邀请码是V3K234

**Comment by cg-xuy** [comment]
问题已确认，奖励会在3个工作日内发放，感谢支持！
