### ISSUE TITLE
fox.one app 钱包通知中心的交易订单详情页面报 "Internal Server Error"错误。

### ISSUE THREAD

**Issue by mosjin** [fox-one/bugs-hunter#119]
fox.one app 钱包通知中心的交易订单详情页面报 "Internal Server Error"错误。

**1. 平台:**
Android 2.11.0(215) 华为手机 10.0

**2. 重现步骤:**
1).打开fox.one app.
2). 依次点击/操作: 
发现=>签到与活动=>特邀任务（FOXONE新节点启动）立即参加=>输入xin的数量=>点加入=>成功

3). 依次点击/操作:
钱包=>通知中心=>点交易=>订单详情: 

报错 **Internal Server Error**

![Internal Server Error](https://user-images.githubusercontent.com/3736908/75241314-d4b38300-5800-11ea-9ccb-b13a13abee1c.jpg)

**Comment by cg-xuy** [comment]
您好，请留下 Fox.ONE 邀请码以便发放奖励，谢谢

**Comment by mosjin** [comment]
> 您好，请留下 Fox.ONE 邀请码以便发放奖励，谢谢

我的邀请码: 
PM5GGV

**Comment by riririridiculous** [comment]
问题已修复，谢谢反馈
