### ISSUE TITLE
iOS 版App内氢定投“更多功能”区按钮问题

### ISSUE THREAD

**Issue by saymoon** [fox-one/bugs-hunter#12]
**描述错误**
右划返回氢定投首页后，之前点过的“更多功能”区的按钮一直loading且无法再次点击

**重现**
重现行为的步骤：
1.打开App - 发现 - 小程序 - 氢定投
2.点击“更多功能”区的任意按钮跳转到对应页面
3.通过右划手势返回氢定投首页
4.问题出现：刚才点过的按钮一直显示为loading状态且无法再次点击

**预期行为**
按钮始终应为可点击状态

**截图**
![IMG_AB6CAD017A0E-1](https://user-images.githubusercontent.com/63803/68943803-26eb0e00-07e7-11ea-9823-e669e1ab1844.jpeg)

**环境信息（请填写以下信息）：**
  - 操作系统：iOS 13.2.2
  - 设备：iPhoneX
  - Fox.ONE 版本 2.7.1(341)
  - Fox.ONE 邀请码 EPRN5Q

**其他内容**

**Comment by divisey** [comment]
这里是因为点击按钮以后，页面正在跳转
