### ISSUE TITLE
改进: ”FOXONE 节点计划页面“ 最好加入用户”已参与值“提示, 否则参与成功后无法知道结果。

### ISSUE THREAD

**Issue by mosjin** [fox-one/bugs-hunter#120]
”FOXONE 节点计划页面“ 最好加入 **”已参与值“** 提示, 否则成功参与后无法知道结果。

**1. 平台:**
Android 2.11.0(215) 华为手机 10.0

**2. 重现步骤:**
1).打开fox.one app.
2). 依次点击/操作:
发现=>签到与活动=>特邀任务（FOXONE新节点启动）立即参加=>输入xin的数量=>点加入=>成功

**3. 期望结果:**
在参与”FOXONE 节点计划页面“加入 **当前参与值** 提示信息。

**Comment by cg-xuy** [comment]
需要后续开发，这一块以后会大改版，感谢建议！建议奖励会在3个工作日内发放！

**Comment by mosjin** [comment]
> 需要后续开发，这一块以后会大改版，感谢建议！建议奖励会在3个工作日内发放！

好的。期待。
