### ISSUE TITLE
输入pin码后无法进入钱包，一直循环让输入pin

### ISSUE THREAD

**Issue by hongxiaojun** [fox-one/bugs-hunter#121]
Fox one版本号 2.11.0(381
iphone X ios 13.3.1
邀请码 3V74XG
有录屏，我的mixin id 34855
Bug如下
![A37ECCCE-549F-4015-BA34-0A56C2444979](https://user-images.githubusercontent.com/35869352/75404611-08e48c00-5946-11ea-9eb5-e5ca8a121ff7.png)
![7EDAC236-0D9E-4B5A-B5F6-7768B311508A](https://user-images.githubusercontent.com/35869352/75404615-0c781300-5946-11ea-8779-237054779a01.png)

**Comment by cg-xuy** [comment]
已知问题，这里其实是网络原因导致的。
针对这个问题，新版本会修改错误提示；网络问题会在近期彻底优化掉。
感谢反馈，给您送上 FC 积分奖励，将于 3 个工作日内发放！
