### ISSUE TITLE
F2 组建阶段补贴数额不对

### ISSUE THREAD

**Issue by liusining** [fox-one/bugs-hunter#122]
**描述错误**
页面显示筹集进度在 8000 - 11000 之间，按照[公告](https://fox.zendesk.com/hc/en-us/articles/360038685791-F2-Fox-ONE-new-Mixin-Node)，单日补贴总额应为 0.3 XIN/天，但实际补贴量却是 0.1 XIN/天。目测错误从 2020/02/26 开始发生。

**重现**
重现行为的步骤：
1.参与 F2 筹集
2.计算所得数量：（自己单天得到的补贴XIN数量 / 自己的F2数量）* 约8000多的F2总量 = XIN补贴总量
3.发现 XIN补贴总量 = 0.1 XIN/天

**预期行为**
纠正补贴数量，或者解释数量为什么和公告不符

**环境信息（请填写以下信息）：**
  - Fox.ONE 邀请码 [RYX62M]

**Comment by cg-xuy** [comment]
感谢反馈，已经调整，奖励会在三个工作日内发放！
