### ISSUE TITLE
FCF指数okex数据不显示

### ISSUE THREAD

**Issue by teomgd** [fox-one/bugs-hunter#123]
**描述错误**
数据一栏 FCF指数中 okex的数据不显示

**重现**
重现行为的步骤：
1.转到“ 发现”
2.点击“ 数据”
3.向下滚动到“ FCF”
4.点击FCF
5. 向下滚动到 OKEX 
6. 点击 OKEX
7.    看到错误。 okex数据都显示为0

**环境信息（请填写以下信息）：**
  - 设备：[iphone x ]
  - 操作系统：[iOS 13.3.1]
  - 手机系统语言 [中文]
  - Fox.ONE 版本 [2.11.1]
  - Fox.ONE 邀请码 [DZM36Q]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by cg-xuy** [comment]
您好，感谢反馈，奖励会在三个工作日内发放。
