### ISSUE TITLE
币多多逻辑漏洞

### ISSUE THREAD

**Issue by zed-wong** [fox-one/bugs-hunter#128]
币多多逻辑漏洞：虽然限制最大购买量，但是可以通过多次购买绕过限制
![IMAGE_20200316_2006337881453768302147862](https://user-images.githubusercontent.com/36271125/76756991-bfa78f80-67c1-11ea-871f-5e49ca9902d8.jpg)
![IMAGE_20200316_2006267041411421831998484](https://user-images.githubusercontent.com/36271125/76757026-ccc47e80-67c1-11ea-8109-3a227689cb19.jpg)

foxone邀请码:7KR386

**Comment by cg-xuy** [comment]
问题已确认，暂时可能不会修复，奖励会在3个工作日内发放，感谢支持。
