### ISSUE TITLE
币多多支付逻辑问题

### ISSUE THREAD

**Issue by BZCG** [fox-one/bugs-hunter#131]
**描述错误**
在币多多买完理财标定输入密码后，会显示正在检查支付结果，此时下方会出现一个取消键，经过几次尝试，发现其作用是不符合逻辑的，如果点了取消应该是终止支付进程，而实际作用只有退出（正在检查支付结果)，最终依然是支付成功。

**预期行为**
点击取消后，支付失败。
Mixin ID:37378503

**Comment by cg-xuy** [comment]
您好，取消的作用是取消 loading ，不能取消实际的订单，订单的取消在 我的订单 页面。后面会优化，当发现有未支付订单时，直接跳转到订单页。
