### ISSUE TITLE
币多多优化建议

### ISSUE THREAD

**Issue by BZCG** [fox-one/bugs-hunter#132]
建议在转入理财标定的时候加入钱包余额显示，不然非整数转入会很繁琐。

**Comment by riririridiculous** [comment]
嗯嗯 这个在我们的排期内的 感谢！

**Comment by cg-xuy** [comment]
同 #129 近期会优化，感谢提醒！提交 issue 的时候，建议加上自己的 Fox.ONE App 的邀请码，方便奖励的发放。
