### ISSUE TITLE
交易手续费错误

### ISSUE THREAD

**Issue by hongxiaojun** [fox-one/bugs-hunter#135]
Fox one版本号 2.11.1  iphone X ios 13.3.1  邀请码 3V74XG
Bug如下，总成交额数据明显错误
![image](https://user-images.githubusercontent.com/35869352/77153011-f1776980-6ad3-11ea-80f7-e05f2bb31d5b.png)

**Comment by cg-xuy** [comment]
问题已确认，奖励会在3个工作日内发放，感谢支持。

**Comment by cg-xuy** [comment]
> 问题已确认，奖励会在3个工作日内发放，感谢支持。

问题已经明确，在新版本中会修复掉。
