### ISSUE TITLE
关于交易详情页关闭按钮挡住信息的问题

### ISSUE THREAD

**Issue by wanglonghuan** [fox-one/bugs-hunter#138]
**描述错误**
账户页，点击具体的增减记录页，关闭按钮挡住了信息，可以调整到左上角或又上角

**重现**
看截图
**预期行为**
关闭按钮 别挡住信息，可以放到左上角或又上角

**截图**
![606263BB-22DB-4415-8D51-C2EEF092DE73](https://user-images.githubusercontent.com/11649629/77325643-9f447b80-6d53-11ea-94aa-9cd8b0590127.png)

**环境信息（请填写以下信息）：**
  - 操作系统： iOS
  - 浏览器 [例如 Chrome]
  - 版本 [例如 22]
  - 设备：[例如 iPhone 6]
  - 操作系统：[例如 iOS 8.1]
  - 版本 [例如 22]
  - 手机系统语言 [中文]
  - Fox.ONE 版本 [例如 2.7.0]
  - Fox.ONE 邀请码 [在“邀请朋友”中获取]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by riririridiculous** [comment]
感谢反馈，会在新版中优化该问题！

**Comment by cg-xuy** [comment]
您好，请提供您的邀请码，方便发放奖励。

**Comment by wanglonghuan** [comment]
邀请码：37MJY4




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xuy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 晚上6:55
收件人:&nbsp;"fox-one/bugs-hunter"<bugs-hunter@noreply.github.com&gt;;
抄送:&nbsp;"longhuan"<422181862@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fox-one/bugs-hunter] 关于交易详情页关闭按钮挡住信息的问题 (#138)





 
您好，请提供您的邀请码，方便发放奖励。
