### ISSUE TITLE
[Fox.ONE]签到下小程序在余额不足时支付, 关闭提示框后，3s后自动弹出"正在获取支付结果"信息

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#14]
**描述错误**
签到小程序，"现在补签"链接点击后，选择支付，提示余额不足后，取消，不做任何操作，界面将自动弹出"正在获取支付结果"信息框； 
关闭信息框，再次点击 xxFC 按钮，会弹出补签页面，同时会一直在补签页面后出现“正在获取支付结果”及取消按钮。

**重现**
重现行为的步骤：
1.进入【签到】小程序
2.点击补签"现在补签"链接
3.选择【补签6天】框中的"60FC"按钮（我当前是有6天未签到）
4.点击弹出框中的支付按钮
5.提示余额不足，此时点击取消
6.提示“正在获取支付结果”，并出现取消按钮
7.点击取消
现象一：
 8. 稍等一会(3s), 继续弹出：“正在获取支付结果”，并出现取消按钮
现象二：
 8. 点击取消后，再次点击【补签6天】框中的"60FC"按钮
 9. 同时呈现补签页面，并在补签页面后面出现“正在获取支付结果”页面和取消按钮。

**预期行为**
1. 余额不足，点击取消后，不应该一直弹出: "正在获取支付结果”，并出现取消按钮
2. 取消后，第二次点击 “60FC”按钮后，在随后补签弹出框，选择“取消”后，不应该后面出现“正在获取支付结果”显示。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![1](https://user-images.githubusercontent.com/57244821/68945113-99112200-07ea-11ea-978f-b486fb9bf1af.png)
![2](https://user-images.githubusercontent.com/57244821/68945123-9e6e6c80-07ea-11ea-9bd0-c930b7168c7d.png)
![3](https://user-images.githubusercontent.com/57244821/68945133-a201f380-07ea-11ea-8bc8-89a68b7c661d.png)
![4](https://user-images.githubusercontent.com/57244821/68945144-a6c6a780-07ea-11ea-8d3b-bc7e8acecdd0.png)
![5](https://user-images.githubusercontent.com/57244821/68945157-aaf2c500-07ea-11ea-855c-32bd1a50179f.png)
![6](https://user-images.githubusercontent.com/57244821/68945163-ad551f00-07ea-11ea-9741-2f265f0d082c.png)

**环境信息（请填写以下信息）：**
  - 操作系统：[ Android 8.0.0 ]
  - 浏览器 [无关 ]
  - 版本 [无关]
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08

  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
无

**Comment by xuyan1214** [comment]
没有回调，暂不处理。
