### ISSUE TITLE
[小钱包]币种转账记录显示错误

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#146]
**描述错误**
A币种的转账记录上的数字和转账对象显示的是B币种的。

**重现**
重现行为的步骤：
1.在 mixin 对话框点击小钱包机器人图标 
2.点击“ BOX”, 看到转账记录
3.点击左上角左箭头返回
4.点击“ XIN”
5.看到错误：转账记录的数字和转账对象与BOX的一模一样
6.退出重进后显示正确的转账记录

**预期行为**
看到正确的转账记录

**截图**
![截图1](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gdeom99332j30ku112drg.jpg)
BOX的转账记录

![截图2](https://wx3.sinaimg.cn/mw690/007nqC8Ygy1gdeoma6m3lj30ku112149.jpg)
XIN的转账记录的数字与BOX的一模一样

![截图3](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gdeomb332fj30ku112n8k.jpg)
XIN 正确的转账记录

**环境信息（请填写以下信息）：**

- Fox.ONE 邀请码 [Z6WGNY]
- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 13.3.1]
- mixin 版本 [0.22.1（305)]
- Fox.ONE 邀请码 [DNR42M]

**其它**
这个现象我碰到次数也不多，退出重进会就正常了。印象中一般点进一个币种，每个转账记录的位置上会显示刷新的进度条，进度条结束了，就可以看到具体的转账记录了。但是这种情况下是没有刷新的过程的，转账记录是直接显示出来的。

**Comment by cg-xuy** [comment]
这种情况看起来像是网络的问题，我试了下，没办法复现，下次遇到，点击右上角三个点，刷新下试试。
