### ISSUE TITLE
Fox.ONE通知中心：中文页面,日期呈现英文月份缩写

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#15]
**描述错误**
Fox.ONE通知中心：中文页面,日期呈现英文月份缩写

**重现**
重现行为的步骤：
1.点击"钱包"导航按钮
2.点击右上角 "通知铃铛"
3. 通知中心的信息中，混用中英文（消息的日期中使用英文月份缩写）
**预期行为**
中文界面，应该采用中文日期写法

**截图**
![A1](https://user-images.githubusercontent.com/57244821/68945988-c2cb4880-07ec-11ea-807d-7d2cab93f874.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
无

**Comment by xuyan1214** [comment]
与 #17 问题类型重复。
