### ISSUE TITLE
[Fox.ONE]中文系统中，会员页面进入时出现英文提示"Membership"

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#17]
**描述错误**
中文系统中，会员页面进入时出现英文提示"Membership"

**重现**
重现行为的步骤：
1. 点击会员按钮条

**预期行为**
 中文系统，不出现 英文提示和界面信息

**截图**
![A3-2](https://user-images.githubusercontent.com/57244821/68947124-ada3e900-07ef-11ea-9f49-a66b77f5a623.png)
![A3](https://user-images.githubusercontent.com/57244821/68947129-b09ed980-07ef-11ea-8783-17eadac1aeea.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
无

**Comment by divisey** [comment]
fixed
