### ISSUE TITLE
[Fox.ONE]小程序点亮BOX,进入后，单次按小米手机"返回键",小程序页面无法返回

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#19]
**描述错误**
小程序点亮BOX,进入后，按返回键无法返回

**重现**
重现行为的步骤：
1.点解小程序：点亮BOX
2.按物理“返回键”，只是刷新当前页面，无法退出
3.快速按两次以上后，可以退出

**预期行为**
 按返回键可以退出

**截图**
![A5](https://user-images.githubusercontent.com/57244821/68949933-155d3280-07f6-11ea-827a-7904ce2782d2.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
 未尝试其他手机，测试用的是小米5s plus

**Comment by xuyan1214** [comment]
目前 Mixin messenger 里小程序也会有类似问题，解决成本较高，暂不处理。
