### ISSUE TITLE
IOS版氢定投页面无返回问题

### ISSUE THREAD

**Issue by Byfindit** [fox-one/bugs-hunter#2]
**描述错误**

iOS版在“氢定投”界面点“zotc”反应很慢，要5s以上或者死掉；同时进入后无法返回。

**重现**
重现行为的步骤：
1.转到“ 发现”-“小程序”-“氢定投”
2.点击“ ..开始..”—“充值”—“去zotc”
3.向上滚动，
4.看到错误，没有返回🔙

**预期行为**
无法返回，或等待较长时间，影响体验

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息（请填写以下信息）：**
  - 操作系统：【iOS]
  - 浏览器 [自带
 
  - 设备：[iPhone 7p]
  - 操作系统：[例如 iOS 8.1]
  - 版本 [例如 22]
  - Fox.ONE 版本 [2.7.0]
  - Fox.ONE 邀请码 DKJRR7

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by Byfindit** [comment]
![Uploading D6CC0BB8-7315-4F3F-8FFD-9F6EB54BAED7.png…]()
![Uploading A631042F-21F7-4740-B049-CA7656D10DA3.png…]()

**Comment by riririridiculous** [comment]
![IMG_2798](https://user-images.githubusercontent.com/39544891/68551700-927d5600-044a-11ea-9c96-68e394693e8e.PNG)

**Comment by divisey** [comment]
在点击 前往ZOTC页面 以后，浏览器会加载 ZOTC 的页面。这里的描述的问题原因是网络不好的情况下页面加载太慢，看上去好像没有反应一样。
【优化方案/已发布】用户点击 前往ZOTC页面 以后将 BUTTON 置为 LOADING 状态。

**Comment by xuyan1214** [comment]
done
