### ISSUE TITLE
[Fox.ONE]分享到朋友圈的内容,点击查看是提示"访问令牌错误"和"user"

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#20]
**描述错误**
分享到朋友圈的内容,点击查看是提示"访问令牌错误"和"user auth failed"

**重现**
重现行为的步骤：
1.点亮BOX，分享到朋友圈
2.从朋友圈点击信息，弹出的页面中提示"访问令牌错误"和"user auth failed"

**预期行为**
 不清楚。

**截图**
![A6](https://user-images.githubusercontent.com/57244821/68950315-dc718d80-07f6-11ea-80ab-4f34bce340c0.png)

**环境信息（请填写以下信息）：**
  - 版本 [微信 7.0.7]
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
无

**Comment by riririridiculous** [comment]
fixed
