### ISSUE TITLE
[Fox.ONE]发现页设置由"默认"改为"英文", 此时退出设置页面并进入发现页，内容未切换,再次点击某些专题后内容才变为英文

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#21]
**描述错误**
发现页设置由"默认"改为"英文", 在发现页内容未切换,点击某些专题后内容才变为英文

**重现**
重现行为的步骤：
1.设置->发现页设置->资讯设置-> 默认改为英文
2.切换到 发现 页，查看信息
3.发现页首页内容仍然为中文。
4.点击 "最新"等主题，此时返回信息为英文

**预期行为**
设置了发现页的资讯为英文后，发现页的首页也应该为英文资讯。

**截图**
![A7-1](https://user-images.githubusercontent.com/57244821/68951174-81d93100-07f8-11ea-8a6f-8046817b09ef.png)
![A7-2](https://user-images.githubusercontent.com/57244821/68951186-86054e80-07f8-11ea-9b80-d0d672edf399.png)
![A7-3](https://user-images.githubusercontent.com/57244821/68951192-89003f00-07f8-11ea-8f13-63ee12bf9d8d.png)
![A7-4](https://user-images.githubusercontent.com/57244821/68951195-8bfb2f80-07f8-11ea-89dd-3f7aad2f3c6b.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
 无。

**Comment by liupeng-hub** [comment]
另外 发现页设置中，“默认”的含义不明确；

**Comment by firefly1126** [comment]
🐛 FIXED
