### ISSUE TITLE
[Fox.ONE]中文系统时间为2019-11-15 23点,资讯文章的日期出现2019-11-16

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#22]
**描述错误**
中文系统时间为2019-11-15 23点,资讯文章的日期出现2019-11-16

**重现**
重现行为的步骤：
1.查看资讯文章的日期，系统时间2019-11-15 23点，显示文章时间为未来时间2019-11-16

**预期行为**
时间正确显示

**截图**
![A8-1](https://user-images.githubusercontent.com/57244821/68954286-af28dd80-07fe-11ea-813d-10f3eead1c4e.png)
![A8-2](https://user-images.githubusercontent.com/57244821/68954293-b354fb00-07fe-11ea-86bc-502c6465ecf5.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
 无

**Comment by xuyan1214** [comment]
赏金会在3个工作日内发放，谢谢支持。
