### ISSUE TITLE
[[Fox.ONE 中氢定投]]设置定投周期时,下拉列表每周/每日/每月的排列顺序建议改为每日/每周/每月

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#23]
**描述错误**
设置定投周期时,下拉列表每周/每日/每月的排列顺序不太符合常规

**重现**
重现行为的步骤：
1.[氢定投]设置定投周期时
2. 点击"周期"，弹出框列表

**预期行为**
排列顺序，从小到大，可能更匹配用户认知
 每日
 每周
 每月

**截图**
![A9](https://user-images.githubusercontent.com/57244821/68955696-88b87180-0801-11ea-8382-aab19994ddbd.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
 无

**Comment by riririridiculous** [comment]
这是个 feature 不修改了，谢谢！

**Comment by lyricat** [comment]
顺序要改啊，为什么不改

**Comment by xuyan1214** [comment]
赏金会在 3 个工作日内发放，谢谢支持。

**Comment by divisey** [comment]
fixed
