### ISSUE TITLE
[Fox.ONE 中氢定投]小程序在余额不足时提现，提示错误看不懂"insufficient balance"或“invalid traceID”

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#24]
**描述错误**
[氢定投]小程序在余额不足时提现，提示错误看不懂

**重现**
重现行为的步骤：
1.进入我的定投(余额为0）
2.点击提现
3.输入800
4.点击"好的"，提示"insufficient balance"
5.输入088855，提示“invalid traceID”

**预期行为**
中文正确提示用户

**截图**
![A11-1](https://user-images.githubusercontent.com/57244821/68957104-4f353580-0804-11ea-81ff-8e8c0e13107c.jpg)
![A11-2](https://user-images.githubusercontent.com/57244821/68957105-4fcdcc00-0804-11ea-9718-ead5df38ffda.jpg)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
 无

**Comment by divisey** [comment]
已经修复
