### ISSUE TITLE
[Fox.ONE 中氢定投]小程序提示"还可以定投x天",天数不正确

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#25]
**描述错误**
[Fox.ONE 中氢定投]小程序提示"还可以定投x天",天数不正确

**重现**
重现行为的步骤：
1. 创建了两个定投计划，余额当前为0
2. 氢定投 首页，点击 "我的定投"，进入页面，显示**“还可定投0天”**
3. 氢定投 首页，点击“开始”按钮，进入页面，显示**“还可定投1天”**

**预期行为**
 正确展示”还可定投“的天数，天数一致

**截图**
![A11-1](https://user-images.githubusercontent.com/57244821/68959447-0633b000-0809-11ea-9732-28a575a3074c.png)
![A11-2](https://user-images.githubusercontent.com/57244821/68959448-0633b000-0809-11ea-835c-9a4f629fa696.png)
![A11-3](https://user-images.githubusercontent.com/57244821/68959450-06cc4680-0809-11ea-8336-4c6f77d28c22.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by liupeng-hub** [comment]
尝试复现，未成功。备注：期间做个软件呈现语言的中英切换，再次测试时，无法复现问题描述。

**Comment by divisey** [comment]
这里会更改成新的计算逻辑，下次更新会加上。所以这个 issue 可以被关闭了。

**Comment by xuyan1214** [comment]
赏金会在 3 个工作日内发放，谢谢支持。
