### ISSUE TITLE
[MIXIN 小钱包]资产总值不等于列表中分项值之和

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#26]
**描述错误**
[MIXIN 小钱包]资产总值不等于列表中分项值之和

*重现**
重现行为的步骤：
1.打开小钱包

**预期行为**
呈现的总值等于各分项值之和

**截图**
![A12-1](https://user-images.githubusercontent.com/57244821/68995605-6b030f00-08ca-11ea-94ef-043d7a2bfac2.png)
![A12-2](https://user-images.githubusercontent.com/57244821/68995606-6b030f00-08ca-11ea-8f7d-9ef506cfa1d3.png)
![A12-3](https://user-images.githubusercontent.com/57244821/68995613-91c14580-08ca-11ea-9c9f-7f8420814ccd.png)
![A12-4](https://user-images.githubusercontent.com/57244821/68995614-91c14580-08ca-11ea-8dff-a4c6da7cfc6b.png)

**环境信息（请填写以下信息）：**
 
**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
无

**Comment by divisey** [comment]
fix now

**Comment by xuyan1214** [comment]
赏金会在 3 个工作日内发放，谢谢支持。
