### ISSUE TITLE
[Fox.ONE]个人资料页面邮箱旁>按钮点击无反应，邮箱无法编辑

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#27]
**描述错误**
[Fox.ONE]个人资料页面邮箱无法编辑

**重现**
重现行为的步骤：
1. 进入"钱包"导航栏目
2. 点击用户头像，进入用户资料界面
3. 点击邮箱的最右侧>符号，无任何反应，无法编辑邮箱

**预期行为**
可点击>符号后，可查看或编辑邮箱。进而后续可用邮箱登录（看登录界面，有支持邮箱登录）

**截图**
![A13-1](https://user-images.githubusercontent.com/57244821/68995633-d351f080-08ca-11ea-9714-b482dbe8aefe.png)

**环境信息（请填写以下信息）**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**无

**Comment by xuyan1214** [comment]
赏金会在 3 个工作日内发放，谢谢支持。
