### ISSUE TITLE
[MIXIN BOX ATM]fox.one中打开box atm机器人，它的标题显示不全

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#28]
**描述错误**
fox.one 打开box atm机器人后，页面中atm标题被fox.one窗口覆盖，显示不全

**重现**
重现行为的步骤：
1. 在MIXIN中fox.one中文群，打开 BOX ATM机器人

**预期行为**
中英文显示条件下，box atm的标题显示验证

**截图**
![A14-1](https://user-images.githubusercontent.com/57244821/68995656-18762280-08cb-11ea-9ef3-b72a2889d28b.png)
![a14-2](https://user-images.githubusercontent.com/57244821/68995657-18762280-08cb-11ea-8bb2-563da71fdd6b.jpg)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by divisey** [comment]
已知BUG，已修复，待发布

**Comment by xuyan1214** [comment]
已知 BUG
