### ISSUE TITLE
[FOX.ONE]公共挂单簿显示异常过一会才正常

### ISSUE THREAD

**Issue by ianwmar** [fox-one/bugs-hunter#29]
**描述错误**
在FMC1/XIN交易对挂了一个买单，返回后重新进入挂单簿查看，发现一开始显示正常很快就消失了，过一会儿才正常。（此外，有个与本问题无关的老问题也顺便提一下，就是挂单成功后在私有的「委托挂单」上显示了但马上就消失了，必须返回到交易大厅重新进入才正常显示）

**重现**
重现行为的步骤：
1. FMC1/XIN交易对挂个买单
2. 返回到交易大厅后重新进入
3. 会看到挂单簿上的买单正常显示但很快就消失了
4. 重复数次或过几秒后才不会有这种现象。

**环境信息（请填写以下信息）：**
  - 操作系统：安卓
  - Fox.ONE 版本：2.7.1
  - Fox.ONE 邀请码 ：85MYMM

**Comment by xuyan1214** [comment]
同 #9
