### ISSUE TITLE
FMI指数归零

### ISSUE THREAD

**Issue by evo-lee** [fox-one/bugs-hunter#3]
fox app数据的 FMI指数归零
版本 IOS 13.1.2 XR 测试 2.7.0
邀请码D655KR

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by evo-lee** [comment]
![06E15AA3-0EC8-42ED-BA05-F3EAA861470E](https://user-images.githubusercontent.com/34160928/68519522-76ec4100-02cc-11ea-9486-15d8e76a44fc.png)

**Comment by evo-lee** [comment]
2019年11月10日早上8点50左右FMI再次归零
![8D535F2C-AD17-4E36-9BDE-E1187C331B25](https://user-images.githubusercontent.com/34160928/68536983-48876800-0397-11ea-9551-220e4adf91c4.png)

**Comment by xuyan1214** [comment]
已修复，奖励会在3个工作日内发放，感谢支持！
