### ISSUE TITLE
一个关于Fox.ONE充值会员后无法增加会员特权的问题报告

### ISSUE THREAD

**Issue by XueAE** [fox-one/bugs-hunter#32]
**描述错误**
用FC充值一个月会员后，FC已被扣，但会员特权并为增加，如：无法领取每日宝箱。

**重现**
重现行为的步骤：
1.点击“ 钱包”
2.点击“ Fox.ONE 会员”
3.看到“会员特权“下”每日宝箱”图标始终为黑色
4.反复数次，退出-重新进入程序，操作系统始终如此。

**预期行为**
购买会员交易成功后，系统及时自动发放会员权益。

**截图**
![微信图片_20191119110001](https://user-images.githubusercontent.com/57041578/69113165-2db2a300-0abd-11ea-8d97-22b56581ad25.png)
![微信图片_201911191100012](https://user-images.githubusercontent.com/57041578/69113175-373c0b00-0abd-11ea-8698-9d868d6338f7.png)

**环境信息（请填写以下信息）：**
  - 操作系统：[iOS]
  - 设备：[iPhone XR]
  - 操作系统：[iOS 13.0]
  - Fox.ONE 版本 [2.7.1]（澳大利亚区）
  - Fox.ONE 邀请码 [PMVRWJ]

**Comment by liupeng-hub** [comment]
记得以前中文群中有说：充值当前不能领取；隔天看下

**Comment by xuyan1214** [comment]
宝箱，是当日瓜分昨日奖池总收益。所以刚开的会员，是无法开宝箱的。不过这里的确可以考虑优化加个提示。
