### ISSUE TITLE
[Fox.ONE]交易时的钱包金额显示为科学计数法,不易理解

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#34]
**描述错误**
[Fox.ONE]交易时的钱包金额显示为科学计数法,不易理解

**重现**
重现行为的步骤：
1.点击"智能买入"

**预期行为**
钱包余额不显示为科学计数法，按小数显示；

**截图**
![A1](https://user-images.githubusercontent.com/57244821/69393631-aa8b8a00-0d14-11ea-9f25-7e8352d74f0f.png)

**环境信息（请填写以下信息）**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
无

**Comment by liupeng-hub** [comment]
卖出时，钱包余额在很少时，数值也按科学计数法显示，不易理解。
![A2](https://user-images.githubusercontent.com/57244821/69393757-03f3b900-0d15-11ea-98ad-54e9f4902d0a.png)

**Comment by xuyan1214** [comment]
奖励将在 3 个工作日内发放，感谢支持。
