### ISSUE TITLE
[Fox.ONE]中文系统中较多非中文提示，建议进行本地化呈现

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#36]
**描述错误**
中文系统中较多非中文提示

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
界面尽量本地化呈现

**截图**
![1](https://user-images.githubusercontent.com/57244821/69398615-f4c93700-0d25-11ea-9ac2-a5b8eb3c61df.png)
![2](https://user-images.githubusercontent.com/57244821/69398616-f4c93700-0d25-11ea-8793-369fb9c79672.png)
![3](https://user-images.githubusercontent.com/57244821/69398618-f561cd80-0d25-11ea-8c92-5ecb0734e822.png)
![4](https://user-images.githubusercontent.com/57244821/69398619-f561cd80-0d25-11ea-890f-7b3bf4e8cee6.png)
![6](https://user-images.githubusercontent.com/57244821/69398620-f561cd80-0d25-11ea-9c78-0ac400454954.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by xuyan1214** [comment]
奖励将会在 3 个工作日内发放，感谢支持。
