### ISSUE TITLE
[Fox.ONE]版本更新后,版本说明中没有最新版本的信息

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#37]
**描述错误**
版本更新后,版本说明中未有最新版本的信息

**重现**
重现行为的步骤：
1.转到“ 钱包”
2.点击“ 关于”
3.点击“版本说明”

**预期行为**
存在最新版说明信息

**截图**
![1](https://user-images.githubusercontent.com/57244821/69398874-fe06d380-0d26-11ea-87e5-4d76592d3204.png)
![2](https://user-images.githubusercontent.com/57244821/69398875-fe06d380-0d26-11ea-8099-5ee959977db1.png)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.8.0 ] 2019-11-22
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by xuyan1214** [comment]
暂不解决。
