### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by hongxiaojun** [fox-one/bugs-hunter#38]
**描述错误**
点开软件，停留在行情界面，无操作，15秒后提示软件已崩溃。

**截图**
![FE46B9F3-34EC-473C-BA1D-66B2F286E5CA](https://user-images.githubusercontent.com/35869352/69470065-1b8f7800-0dcf-11ea-9b1c-7020091ff1e8.png)

**环境信息（请填写以下信息）：**
  - 设备： iPhone x
  - 操作系统： iOS 13.1.3

  - Fox.ONE 版本2.8.0（350）
  - Fox.ONE 邀请码 3V74XG

**Comment by xuyan1214** [comment]
你好，这个没办法复现。如果方便，可能得提供更为详细的描述，否则没办法解决。

**Comment by lyricat** [comment]
没有更多信息的话，这个 issue 就关闭了。
