### ISSUE TITLE
ss节点收到的xin无价格

### ISSUE THREAD

**Issue by hongxiaojun** [fox-one/bugs-hunter#39]
**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息（请填写以下信息）：**
  - 操作系统：[例如 iOS]
  - 浏览器 [例如 Chrome]
  - 版本 [例如 22]
  - 设备：iPhone 10
  - 操作系统：iOS 13.1.3
  - Fox.ONE 版本 2.8.0
  - Fox.ONE 邀请码 [在“邀请朋友

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by xuyan1214** [comment]
你好，问题描述以及环境信息提供不全。方便的话，建议提供更为完整的信息，包括页面截图。

**Comment by riririridiculous** [comment]
虽然描述不是太清晰，但这个是已知问题，新版本已经修复，谢谢！
