### ISSUE TITLE
Android 9 error tab

### ISSUE THREAD

**Issue by fithozee** [fox-one/bugs-hunter#4]
This error is in Explore tab that cannot be open.

**Comment by xuyan1214** [comment]
More details about the error and add your Fox.ONE Referral Code please.

**Comment by fithozee** [comment]
479RZK REFF Code, i cant upload the screenshot. Its error in Explore tab

**Comment by xuyan1214** [comment]
Most pages are required to be opened in Fox.ONE app.  Why do you want to open it in Explore tab? And could you please provide the link?

**Comment by fithozee** [comment]
Its error in the Explore menu on the app, chat mixin 37752853 if you want the screenshot.

**Comment by fithozee** [comment]
Now its fixed , i just reported to firefly
