### ISSUE TITLE
[氢定投]USDT余额无法提取

### ISSUE THREAD

**Issue by louissimons** [fox-one/bugs-hunter#40]
**描述错误**
氢定投内USDT充值后，无法提现

**重现**
重现行为的步骤：
1.进入『氢定投』
2.点击『充值』，从钱包中转入USDT-ERC20
3.点击『+』，创建BOX定投计划（每周2上午9:00 投145USDT）
4.暂停定投计划
5.点击『提现』，输入任意金额，提示『提现数量超出可用余额』

**预期行为**
提现到Fox.one钱包

**截图**
![image](https://user-images.githubusercontent.com/1994979/69591615-2d228b00-102e-11ea-9fde-9d5829bebda2.png)

**环境信息（请填写以下信息）：**
  - 操作系统： iOS
  - 浏览器：——
  - 版本：——
  - 设备：iPhone XS max
  - 操作系统： iOS 13.3
  - 版本：——
  - Fox.ONE 版本： 2.8.0(349)
  - Fox.ONE 邀请码：479VY9

**其他内容**
暂无

**Comment by xuyan1214** [comment]
已修复。赏金会在 3 个工作日内发放，感谢支持！
