### ISSUE TITLE
关于“通知”隐私保密

### ISSUE THREAD

**Issue by hongxiaojun** [fox-one/bugs-hunter#41]
**描述错误**
通知没有设置隐私保护。

目前客户端通知栏通知消息全部在未解锁时就可以查看，特别是转账记录，交易记录，这些隐私信息，建议设置在在输入pin码后才可以查看
  - Fox.ONE 邀请码 3V74XG

**Comment by lyricat** [comment]
所以不要把手机给别人呀。

**Comment by lyricat** [comment]
看通知也要输入 PIN 过于不便，没必要。
