### ISSUE TITLE
邀请页面小标题错误

### ISSUE THREAD

**Issue by zccgoodjob** [fox-one/bugs-hunter#42]
- Bug 出现的环境：Fox.ONE 版本（2.8.0）平台（IOS）、机型(iphone 6plus)

- Bug 描述质量:钱包-邀请好友页面  我的邀请人显示的是：我的邀请人。下面的标题应该是：我邀请人人。而App上，我邀请的人写成了：我的邀请人。
- Bug 重现步骤.：点击钱包-邀请好友-页面即可看到。

**Comment by zccgoodjob** [comment]
我的邀请码：8mv789

**Comment by lyricat** [comment]
确认 bug
