### ISSUE TITLE
一个关于Fox.ONE区块评级页面UI问题的报告

### ISSUE THREAD

**Issue by zccgoodjob** [fox-one/bugs-hunter#43]
**描述错误**
发现-数据-区块链评级页面的币种排名UI背景色应该是白色。可是在我的手机上却是灰白相间的颜色，非常难看。

**重现**
重现行为的步骤：
1.转到“ 发现 -  数据 .”
2.点击“区块链评级”
3.看到错误

**预期行为**
希望统一变成白色的UI。

**环境信息（请填写以下信息）：**
  - 操作系统：[ iOS]
  - 版本 [11.4.1]
  - 设备：[ iPhone 6plus]
  - Fox.ONE 版本 [2.8.0]
  - Fox.ONE 邀请码 [8mv789]

**其他内容**

**Comment by riririridiculous** [comment]
已知 BUG，谢谢
