### ISSUE TITLE
一个关于资讯页面专题字体UI格式的问题报告

### ISSUE THREAD

**Issue by zccgoodjob** [fox-one/bugs-hunter#44]
**描述错误**
资讯页面专题字体UI格式在左下方显得不和谐
**重现**
重现行为的步骤：
1.转到“ 首页”
2.点击“ 发现”
3.点击“ 资讯”
4.在专题项目看到错误

**预期行为**
我希望这个专题的页面能够把字体放到中间，框框能够变小点，更好看

**截图**

![](https://wx3.sinaimg.cn/mw690/9aef787cgy1g9jydb3elij20u01hcjut.jpg)

**环境信息（请填写以下信息）：**
  - 操作系统：[iOS]
  - 版本 [例如 22]
  - 设备：[ iPhone 6 Plus]
  - 操作系统：[ iOS 11.4.1]
  - Fox.ONE 版本 [2.8.0(349)]
  - Fox.ONE 邀请码 [8mv789]

**Comment by lyricat** [comment]
这不是 bug
