### ISSUE TITLE
一个关于通知页资产价格不显示的问题的报告

### ISSUE THREAD

**Issue by zccgoodjob** [fox-one/bugs-hunter#47]
描述错误
点击钱包，右上方的小铃铛，进入转账页面后，发现转账的资产无法显示美元价值
重现
重现行为的步骤：
1.转到“ 钱包
2.点击“ 右上方小钟形图标”
3.点击“ 其中的一项转账记录”
4.在转账详情页面看到错误，如下截图

预期行为
点进去就能看到资产价值。还有一个地方需要注意就是，只要你打开了钱包，再进入转账详情页面就可以看到资产标识了。

截图
![image](https://user-images.githubusercontent.com/12016898/70305359-21f60900-183f-11ea-8bd7-aa17234ae89a.png)

环境信息（请填写以下信息）：

操作系统：[iOS]
版本 [例如 22]
设备：[ iPhone 6 Plus]
操作系统：[ iOS 11.4.1]
Fox.ONE 版本 [2.8.0(349)]
Fox.ONE 邀请码 [8mv789]

**Comment by xuyan1214** [comment]
已知问题。
