### ISSUE TITLE
续费会员显示bug

### ISSUE THREAD

**Issue by evo-lee** [fox-one/bugs-hunter#48]
版本:IOS 测试 2.8.0
手机：iPhone XR 13.1.3
邀请码：D655KR

我的积分够一年的会员续费了，但我查看其它付款方式的时候发现这个bug,不显示。
![08BB8585-D520-416A-A24C-10361E9A5012](https://user-images.githubusercontent.com/34160928/70315516-b74fc800-1854-11ea-97e1-58217bbfc7af.png)
![6556B435-1E8A-466F-B159-E0AAFB9262F8](https://user-images.githubusercontent.com/34160928/70315517-b7e85e80-1854-11ea-81f8-ecc1d22615b8.png)
![A6B14EAF-F11F-465C-9FD9-8730915655D9](https://user-images.githubusercontent.com/34160928/70315518-b7e85e80-1854-11ea-929e-7931a4bb3a4b.png)

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by lyricat** [comment]
没看明白...

**Comment by evo-lee** [comment]
> 没看明白...
图一点进去后有fc支付和数字资产支付
图二换到一年用fc支付栏，顶上的用fc和数字资产支付消失
图三再换回用Fc支付一个月，顶上的用fc支付和用数字资产支付仍然缺失
![74B3EFBB-F2A6-4807-95AE-D35681C7CB4B](https://user-images.githubusercontent.com/34160928/70383161-fd677180-19a3-11ea-9652-47fc476f0bb8.jpeg)
![F08605B7-2914-4750-B796-8249592F4815](https://user-images.githubusercontent.com/34160928/70383162-fe000800-19a3-11ea-9aa7-d5244af99104.jpeg)
![F69F9744-2F7C-4F51-9553-5BF1EE738E14](https://user-images.githubusercontent.com/34160928/70383163-fe000800-19a3-11ea-8397-6047f242b678.jpeg)

**Comment by xuyan1214** [comment]
的确存在问题。

**Comment by xuyan1214** [comment]
奖励会在3个工作日内发放，感谢支持。

**Comment by divisey** [comment]
fixed
