### ISSUE TITLE
Wrong calculating bugs

### ISSUE THREAD

**Issue by fithozee** [fox-one/bugs-hunter#50]
**Describe the bug**
Wrong number while withdraw

**To Reproduce**
1. Go to withdraw any tokens
2. choose send to mixin messenger
3. Withdraw balance

**Screenshots**
![Screenshot_2019-12-11-11-57-07-393_com fox one](https://user-images.githubusercontent.com/57563502/70593586-30ae3880-1c10-11ea-8056-7ae8cd895b8b.png)

![Screenshot_2019-12-11-11-57-12-801_com fox one](https://user-images.githubusercontent.com/57563502/70593691-8e428500-1c10-11ea-9855-4e11ca18a774.png)

**Information:**
 - Fox.ONE Version [e.g. 2.8.0]
 - Fox.ONE Referral Code 479RZK
ANDROID 9
XIAOMI MI 9T PRO

**Additional context**

**Comment by lyricat** [comment]
I  can not reproduce this issue. any additional information?

**Comment by zhdhr0000** [comment]
It's a display error, This bug will be fixed in the next version v2.9.0.

**Comment by xuyan1214** [comment]
Thank you for your support. The reward will be distributed within 3 working days.
