### ISSUE TITLE
App Force close and not responding

### ISSUE THREAD

**Issue by fithozee** [fox-one/bugs-hunter#51]
**Describe the bug**
The app suddenly not responding if we put a larger balance than we have in the wallet

**To Reproduce**
Steps
1. Go to Withdraw any tokens you have
2. Input larger balance than you have
3. The App Will error' and not responding

**Screenshots**
![Screenshot_2019-12-11-12-31-08-700_com fox one](https://user-images.githubusercontent.com/57563502/70594171-40c71780-1c12-11ea-84a5-87967f6756b7.png)
**My balance is 0.0002 BTC, and i try to put 0.0003 BTC,suddenly the app crash and my keyboard stuck**

![Screenshot_2019-12-11-12-31-38-445_com miui home](https://user-images.githubusercontent.com/57563502/70594243-73711000-1c12-11ea-90a1-57bcba92d5e4.png)
See my keyboard stuck until i go to my homepage

**Information:**
 - Fox.ONE Version [e.g. 2.8.0]
 - Fox.ONE Referral Code 479RZK
ANDROID 9
XIAOMI MI 9T PRO

**Comment by lyricat** [comment]
any progress?

**Comment by xuyan1214** [comment]
We have updated the version to 2.9.0, and you can try to see if you still encounter this problem.

**Comment by riririridiculous** [comment]
Fixed. The reward has already sent to your account. Thanks.
