### ISSUE TITLE
【Mixin氢定投】历史记录出文字标题中时间错误

### ISSUE THREAD

**Issue by liupeng-hub** [fox-one/bugs-hunter#53]
**描述错误**
历史记录出文字标题中时间错误

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
呈现最找的时间 作为 历史定投的起点

**截图**
![1](https://user-images.githubusercontent.com/57244821/71300809-520ee180-23d3-11ea-92ce-7ab013e58763.jpg)

**环境信息（请填写以下信息）：**
  - 设备：[ 小米5s plus]
  - 操作系统：[Android]
  - 版本 [Android 8.0.0]
  - Fox.ONE 版本 [ 2.7.0 ] 2019-10-08
  - Fox.ONE 邀请码 [ 9RWK2W ]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by divisey** [comment]
fixed

**Comment by xuyan1214** [comment]
奖励会在7个工作日内发放！感谢支持
