### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by sanchoos469** [fox-one/bugs-hunter#55]
**Describe the bug**
Incorrect percent!  (%) On the main screen!!!

**Screenshots**
![20191224_101018](https://user-images.githubusercontent.com/55536421/71386095-415ea580-2637-11ea-8067-420c8e8880e6.png)

**Information:**
 - Phone Device:  Samsung Galaxy s6 edge
 - Phone OS:   Android 7.0
 - Phone Version   SM-G925F
 - Fox.ONE Version App.  2.9.0
 - Fox.ONE Referral Code  JJWJM7

**Comment by lyricat** [comment]
duplication of #54
