### ISSUE TITLE
iso 2.9.0 app崩溃bug

### ISSUE THREAD

**Issue by evo-lee** [fox-one/bugs-hunter#56]
版本:IOS 测试 2.9.0
手机：iPhone XR 13.3
邀请码：D655KR

我的手机处于20%电量以下的低电量模式，新打开foxapp后，可以看到显示内容，但是无法点击其他任何按钮。
切出去以后，过一会就显示app崩溃了。

充满电无效，只有彻底清除所有数据，重新安装正常了，不知道是不是因为app数据缓存过多的原因。

![18A1443A-DC0A-471D-AC45-E8FBCBB34289](https://user-images.githubusercontent.com/34160928/71427029-3286fa00-26ee-11ea-9c43-31beda0d9a6a.png)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by lyricat** [comment]
无法重现的话我们就不能修正了。
