### ISSUE TITLE
无法签到

### ISSUE THREAD

**Issue by hongxiaojun** [fox-one/bugs-hunter#57]
**环境信息（请填写以下信息）：**
  - 操作系统 IOS13.3
  - 设备：iPhone X
  - 版本 357
  - Fox.ONE 版本2.8.1
  - Fox.ONE 邀请码 3V74XG

提示wrong captcha code
![0CFCB415-B40E-4B7C-B1A3-FFDB74422901](https://user-images.githubusercontent.com/35869352/71431052-49d3e080-270a-11ea-82a1-1348bb87d731.png)

**Comment by divisey** [comment]
> **环境信息（请填写以下信息）：**
> 
> * 操作系统 IOS13.3
> * 设备：iPhone X
> * 版本 357
> * Fox.ONE 版本2.8.1
> * Fox.ONE 邀请码 3V74XG
> 
> 提示wrong captcha code
> ![0CFCB415-B40E-4B7C-B1A3-FFDB74422901](https://user-images.githubusercontent.com/35869352/71431052-49d3e080-270a-11ea-82a1-1348bb87d731.png)

应该是网络问题。请清除缓存，并且在网络通畅的情况下重试几次。

**Comment by divisey** [comment]
fixed，缓存问题

**Comment by xuyan1214** [comment]
您好，这是个已知问题。
iOS 用户操作： 钱包-设置-清楚缓存；
安卓用户，杀掉app然后重新打开，如果不行就在系统里清除一下缓存；
