### ISSUE TITLE
一个氢定投页面bug的报告

### ISSUE THREAD

**Issue by zccgoodjob** [fox-one/bugs-hunter#58]
描述错误
点击发现，小程序，氢定投，点击开始，创建定投计划时出现bug

重现
![image](https://user-images.githubusercontent.com/12016898/71481951-0e84ff00-283b-11ea-9a49-67e40d921956.png)

环境信息（请填写以下信息）：

操作系统：[iOS]
版本 [例如 22]
设备：[ iPhone 6 Plus]
操作系统：[ iOS 11.4.1]
Fox.ONE 版本 [2.8.0(349)]
Fox.ONE 邀请码 [8mv789]

**Comment by divisey** [comment]
fixed

**Comment by xuyan1214** [comment]
奖励会在7个工作日内发放，感谢支持！
