### ISSUE TITLE
补签多扣了FC

### ISSUE THREAD

**Issue by lijishuangg** [fox-one/bugs-hunter#59]
连续签到断签后补签连续扣了20个FC

IOS系统

邀请码：G9Y456

版本2.9.0
![4096C93E-42BA-498A-90BD-26CA2CCBAC95](https://user-images.githubusercontent.com/59297914/71536628-32843580-294c-11ea-8ee1-5ba6c40db3b7.png)

**Comment by xuyan1214** [comment]
奖励会在7个工作日内发放。除了奖励，额外扣掉得 FC 也会给补上，感谢对我们的支持！

**Comment by yiplee** [comment]
已退回 10 FC
