### ISSUE TITLE
入不了群

### ISSUE THREAD

**Issue by messchen** [fox-one/bugs-hunter#60]
**描述错误**
Mixin有人建了个群，可是添加不了

**重现**
重现行为的步骤：

**预期行为**
希望能添加通过

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![0662021A-6335-4FAE-B6C9-A8DC9EFD421D](https://user-images.githubusercontent.com/59307332/71541927-e14f6280-299a-11ea-899a-82109e9f2189.png)
![FAC45348-36BC-4809-AAE0-C6239B4F2D76](https://user-images.githubusercontent.com/59307332/71541928-e14f6280-299a-11ea-881c-d04832e64efa.png)
![7B294CDB-1B10-4604-B747-9F7CCC875F8B](https://user-images.githubusercontent.com/59307332/71541929-e1e7f900-299a-11ea-97db-72cde682b8dc.png)

**环境信息（请填写以下信息）：**
  - 操作系统：[例如 iOS]
  - 浏览器 [例如 Chrome]
  - 版本 [例如 22]
  - 设备：[例如 iPhone 6]
  - 操作系统：[例如 iOS 8.1]
  - 版本 [例如 22]
  - Fox.ONE 版本 [例如 2.7.0]
  - Fox.ONE 邀请码 [在“邀请朋友”中获取]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyricat** [comment]
这问题跟我们没关系。

Sent from my iPhone
