### ISSUE TITLE
小数点和逗号混淆，从而导致下单时价格和数量错误，无法下单交易

### ISSUE THREAD

**Issue by MonsterWong** [fox-one/bugs-hunter#62]
**描述错误**
因为某些地区系统默认的小数点和逗号的功能相反，从而导致在下单的时候提示价格和数量错误，无法修改价格，无法下单交易。

**环境信息（请填写以下信息）：**
  - 设备：iPhone 8
  - 操作系统：iOS 12.2
  - Fox.ONE 版本 2.9.0(361)
  - Fox.ONE 邀请码  E2P7NW
  - 地区，语言设置如下图

![1601545066](https://user-images.githubusercontent.com/40250312/71700559-0e4dac00-2dc5-11ea-800a-ad6e24cd6ee9.jpg)

**重现**

重现行为的步骤：
1.在 app 首页点击任一交易对，此处以 “FMC1/XIN” 举例。
2.点击“ Sell” 按钮，此时默认下单价格为上次成交价格 ，如下图。

![577544927](https://user-images.githubusercontent.com/40250312/71700974-14448c80-2dc7-11ea-80d6-eda7c9d60cd1.jpg)

此时的价格中，“." 表示小数点。在此状态下，**按键全部失效，无法对价格进行修改**，只有删除按钮有效。注意键盘上小数点的地方，显示的是逗号“,"，这是欧洲区法国德国默认的输入习惯。

![1250085610](https://user-images.githubusercontent.com/40250312/71701088-c4b29080-2dc7-11ea-8358-c8d6442b9543.jpg)

3. 此时如果点击左侧任一价格，此处以买一价格为例，则价格变为用逗号“,”取代了小数点“."，同样，这是欧洲区法国德国默认的输入习惯。此时可以修改价格和数量，但是在提交时则会显示 “price invalid" 和 “amount invalid"，导致无法下单， 如下图。

![1635053594](https://user-images.githubusercontent.com/40250312/71701399-7e5e3100-2dc9-11ea-9d88-93101f00079a.jpg)

4. FoxOne 的产品设计得一直很出色，但是此 bug 最终导致无法正常下单交易，严重影响了app使用。希望团队能尽快修复这一bug，谢谢啦！

**加油！**

**Comment by lyricat** [comment]
确认。

**Comment by xuyan1214** [comment]
奖励会在7个工作日内发放，感谢支持！
