### ISSUE TITLE
[Fox.one iOS] 关于“加入会员”页面的语言问题

### ISSUE THREAD

**Issue by upning** [fox-one/bugs-hunter#63]
**描述错误**
在iOS英文系统下，在“加入会员”页面点击底部的“Back”按钮，就会返回到了中文的“会员”页面下。

**重现**
重现行为的步骤：
1.转到“Join”
2.点击底部“Back < ”
3.看到错误的中文页面

**预期行为**
按理应该是正常的系统语言UI，当前情境下为英文。

**环境信息（请填写以下信息）：**
  - 操作系统：iOS
  - 设备：iphone 8
  - 操作系统：iOS 13.3
  - Fox.ONE 版本 2.9.0 (361)
  - Fox.ONE 邀请码 DW552R

**Comment by xuyan1214** [comment]
您好，可否给个截图，目前我这里没办法复现这个问题。

**Comment by riririridiculous** [comment]
#17 同该问题

**Comment by riririridiculous** [comment]
已确认问题 谢谢 
<img width="517" alt="屏幕快照 2020-01-10 下午3 07 40" src="https://user-images.githubusercontent.com/39544891/72132861-02607c00-33bb-11ea-8d5f-96da9f4a8edb.png">

**Comment by xuyan1214** [comment]
奖励将会在3个工作日内发放，感谢对我们的支持！

**Comment by divisey** [comment]
fixed
