### ISSUE TITLE
[iOS] Lucky Bag点击后问题

### ISSUE THREAD

**Issue by upning** [fox-one/bugs-hunter#64]
**描述错误**
在系统语言为英文的会员页面中，点击Lucky Bag后，页面内容无刷新，仅刷新了Header和Bottom Bar。

**重现**
重现行为的步骤：
1.转到“Membership“
2.点击“Lucky Bag”
3.看到错误

**预期行为**
应该是进入到红包页面吧。

**截图**
![image](https://user-images.githubusercontent.com/917037/71707674-5224cd80-2e26-11ea-9313-ef29461f438d.png)

**环境信息（请填写以下信息）：**
  - 操作系统：iOS
  - 设备：iPhone 8
  - 操作系统：iOS 13.3
  - Fox.ONE 版本 2.9.0 （361）
  - Fox.ONE 邀请码 DW552R

**Comment by riririridiculous** [comment]
会员专属的超级红包，需要开通后才会跳转到红包页。
这里的确有 bug，预期行为应是非会员看到的 “Exclusive Rights” 都应灰置，点击后提示开通会员，如下图所示：
<img width="242" alt="屏幕快照 2020-01-10 下午3 22 16" src="https://user-images.githubusercontent.com/39544891/72133684-055c6c00-33bd-11ea-83c5-6d15ea600055.png">

**Comment by divisey** [comment]
fixed
