### ISSUE TITLE
FOXONE app指数图表的时间显示bug

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#65]
**描述错误**
单击数据版块的指数图表的任一位置，显示的时间均为同一个（所有的指数图表都有这个现象），手指在图表上面滑动则不会出现此现象。

**重现**
重现行为的步骤：
1.转到“ 发现”
2.点击“ 数据”
3.点击“ GBI”
4.单击图表任意位置，看到错误的显示时间“ 31/12/2019 18:00:00 ”

**预期行为**
预期显示该点对应的真实时间坐标

**截图**
![截图1, 单击左边位置](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gao6dnz7e9j30ku112q89.jpg)
截图1, 单击左边较早时间，显示  31/12/2019 18:00:00

![截图2, 单击右边位置](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gao6dolb1sj30ku112n2c.jpg)
截图2, 单击中间较晚时间，还是 显示  31/12/2019 18:00:00

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- Fox.ONE 版本 [2.10.0 ]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
使用的是TESTFLIGHT内测版本

**Comment by xuyan1214** [comment]
问题已确认，是个交互的 bug，会偶现。奖励会在 3 个工作日内发放，感谢支持。

**Comment by firefly1126** [comment]
FIXED @xuyan1214
