### ISSUE TITLE
[小钱包]进入交易（ATM）页面后第一次右滑无法退出，第二次右滑方可退出

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#66]
**描述错误**
ios版本的 mixin 进入小钱包的某个资产的交易页面后，右滑退出第一次不成功，第二次右滑才成功退出。

**重现**
重现行为的步骤：
1.在 mixin 畅聊版对话框点击小钱包机器人图标 
2.点击“BTC”
3.点击“ 交易”
4.右滑
5.发现错误：没有返回上一页面，依然是ATM页面
6.再次右滑
7.成功退出ATM页面，回到 BTC 资产详情页

**预期行为**
步骤5返回到 BTC 资产详情页
**截图**
![截图1](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gao7hhcz5bj30ku1120vy.jpg)
截图1, 右滑之后还是回到原来页面

![截图2](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gao7hhwm3mj30ku112h6v.jpg)
截图2, 右滑后预期返回的页面

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- mixin 畅聊版 版本 [0.18.4（263） ]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**

无

**Comment by xuyan1214** [comment]
@riririridiculous 帮忙测试下，我这里是正常的，一次就可以右滑退出交易页面，回到钱包页面。

**Comment by riririridiculous** [comment]
滑动区域，和力度的问题吧。。亲 你用第二次成功的力度再多试几次，貌似没有问题哈！
谢谢反馈哈！
