### ISSUE TITLE
无法签到，跳出一段英文

### ISSUE THREAD

**Issue by evo-lee** [fox-one/bugs-hunter#67]
版本:IOS 测试 2.9.0
手机：iPhone XR 13.3
邀请码：D655KR

今天签到出现的问题，杀掉进程也还会出现
![FEFBA7CF-B837-4BA3-99CF-46F670802B14](https://user-images.githubusercontent.com/34160928/72026718-71ed4300-32b7-11ea-98a4-2e840dde87b6.png)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by riririridiculous** [comment]
谢谢反馈！
可以如下操作：“设置->清除缓存”，再签到试试

**Comment by evo-lee** [comment]
> 谢谢反馈！
> 可以如下操作：“设置->清除缓存”，再签到试试
@riririridiculous 切换网络接入点后可以签到了，可能是个网络问题。

**Comment by xuyan1214** [comment]
已知问题。
