### ISSUE TITLE
一个关于部分机型闪退的问题报告

### ISSUE THREAD

**Issue by Zaisir** [fox-one/bugs-hunter#7]
错误描述：
fox one手机平台发现一栏内小程序全部出现闪退现象
**重现**
重现行为的步骤：
1.转到“ .发现..”
2.点击“ ..小程序..”
3.向下滚动到：签到闪退，点击氢定投、红包、点亮box、奖励中心。
4.看到错误：均出现闪退
预期行为
能够正常使用平台软件
设备环境：
设备型号：vivo Y1A
操作系统：Android 5.1.1
软件版本：PD1510_C_4.21.1
平台名称：FOX ONE
fox one版本：verson2.7.1
邀请码：EJGY6M

**Comment by xuyan1214** [comment]
您好，希望您配合我们，参与测试，协助修复 BUG，通过链接下载测试版本，尝试是否还存在闪退问题。下载链接： https://fir.im/foxonebeta

**Comment by Zaisir** [comment]
您好，我已通过链接重新下载测试版本，经测试，闪退问题未能恢复。闪退现象与之前报告基本一样。

发自我的vivo智能手机

xuyan <notifications@github.com>编写：

**Comment by xuyan1214** [comment]
收到谢谢，需要一些时间排查问题所在！

**Comment by xuyan1214** [comment]
已解决该问题，感谢！提 Issue 的奖励会在三个工作日内发放
