### ISSUE TITLE
按「智能买入」多次的打开新页面问题

### ISSUE THREAD

**Issue by ianwmar** [fox-one/bugs-hunter#70]
**描述错误**
快速连续按「智能买入」多次，就会打开多个页面。意味着要后退也得按多次。照理说，应该在新页面打开之前不响应打开命令才对。

**环境信息（请填写以下信息）：**
  - 操作系统：安卓
  - 版本：最新
  - Fox.ONE 邀请码：85MYMM

**Comment by riririridiculous** [comment]
问题已确认，奖励将于一周内发放，感谢支持。
