### ISSUE TITLE
[FoxONE App]luckycoin授权时未勾选余额，导致无法发送红包且没有找到重新授权的入口

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#71]
**重现**
重现行为的步骤：
1.转到“ 发现“
2.点击“ 小程序”
3.点击“ 红包”
4.看到luckycoin请求授权页面，有个人信息和余额两项，取消勾选余额项，点确认（这一步是根据记忆描述的，因为没找到再次授权的入口）
5.页面出现提示：auth failed
6.进入发红包页面
7.点击“选择一种资产”
8.看到错误：没有币种可供选择
9.点击搜索资产，输入BTC，
10.发现错误：无搜索结果显示，并且页面感觉显示也不正常，感觉像分裂了
11.过了两天，重新尝试发红包，依然是上面的结果
12.找不到自行授权的入口，导致现在无法发红包
**预期行为**
6.重新唤起授权
8.显示币种
10.显示搜索结果
12.重新唤起授权 or 提供自行授权入口

**截图**
![第8步](https://wx2.sinaimg.cn/mw690/007nqC8Ygy1gav2xmkhwsj30ku112ads.jpg)
第8步，选择资产页面无任何币种

![第10步](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gav2xljg7aj30ku112q6f.jpg)
无搜索结果显示，并且页面显示感觉像断层了

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- Fox.ONE 版本 [2.10.0 (366)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
使用的是TESTFLIGHT内测版本

**Comment by divisey** [comment]
fixed

**Comment by riririridiculous** [comment]
新年快乐，问题已修复，奖励将于一周内发放，感谢支持。
