### ISSUE TITLE
[FoxONE App]中文版设置页面有一个不常见的英文单词

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#72]
**描述错误**
中文版设置页面有一个不常见的英文单词 Misc

**重现**
重现行为的步骤：
1.转到“ 钱包”
2.点击“ 设置”
3.看到英文单词 Misc

**预期行为**
预期看到中文或无

**截图**
![截图1](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gav2xm3ojij30ku112n9n.jpg)
设置页面

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- Fox.ONE 版本 [2.10.0 (366)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
使用的是TESTFLIGHT内测版本

**Comment by riririridiculous** [comment]
Misc 是大杂烩的意思，稍后可能会做本地化处理。感谢支持！新年快乐！
