### ISSUE TITLE
eos提现地址的memo保存问题等

### ISSUE THREAD

**Issue by ianwmar** [fox-one/bugs-hunter#73]
**描述错误**
01- 添加eos提现地址时memo部分无法保存，会自动填充为「created by fox.one mixin sdk」。
02- 下图中红字部分的「相同时」应改为「同时」。
03- 「直接转出」来扫描二维码时，有时一直识别不了。同一个二维码用微信马上就识别了。
![截图](https://user-images.githubusercontent.com/47822788/72388239-650d9b00-3760-11ea-950b-c4683bcff609.jpg)

**环境信息（请填写以下信息）：**
  - 操作系统：安卓
  - 版本：最新
  - Fox.ONE 邀请码：85MYMM

**Comment by riririridiculous** [comment]
新版本已修复，奖励已发放请查收，谢谢

**Comment by riririridiculous** [comment]
新版本已修复，奖励已发放请查收，谢谢
