### ISSUE TITLE
给mixin messager转账bcat时日期显示错误

### ISSUE THREAD

**Issue by rockyjia** [fox-one/bugs-hunter#74]
给mixin messager转账bcat时日期显示错误

![03075727-84E4-4A19-A16C-C53914F8A1E4](https://user-images.githubusercontent.com/489225/72416287-4b487400-37b1-11ea-90a2-93e8ca385e00.png)

![75E98327-F8D2-4DBC-B2B9-A637D3042ED8](https://user-images.githubusercontent.com/489225/72416227-27852e00-37b1-11ea-892c-50735c6cab00.png)

**Comment by riririridiculous** [comment]
新年快乐，问题已确认，请留下邀请码以便我们发放奖励

**Comment by yiplee** [comment]
这个是 mixin 那边的问题，他们已经修复了。

**Comment by rockyjia** [comment]
foxone邀请码？5GPVGN
