### ISSUE TITLE
氢定投定投1期时不显示收益率曲线

### ISSUE THREAD

**Issue by iliujixiang** [fox-one/bugs-hunter#75]
**描述错误**
氢定投定投1期时不显示收益率曲线。

**重现**
重现行为的步骤：
1.转到“氢定投”
2.点击“我的定投”
3.点击进行中的“定投计划”，该定投计划只进行1期了
4.看到错误：无收益率曲线。（有价格曲线）

**预期行为**
期望只有1期定投时也有收益率曲线。

（注，第1期买入时间为2020-1-10，今天是2020-1-15。）

**截图**
![氢定投](https://user-images.githubusercontent.com/13399613/72448519-1c062700-37f2-11ea-8706-d26ecf683ed6.jpeg)

**环境信息（请填写以下信息）：**
  - 设备：[Android]
  - 操作系统：[Android 7.1.1]
  - 版本 [坚果手机 Pro 2 ，型号：OS105，软件版本：v6.7.3]
  - 手机系统语言 [中文]
  - Fox.ONE 版本 [2.9.1(198)]
  - Fox.ONE 邀请码 [DNRX3Q]

**Comment by divisey** [comment]
fixed

**Comment by riririridiculous** [comment]
新年快乐，问题已修复，奖励将于一周内发放，感谢支持。
