### ISSUE TITLE
「交易积分」领取页面的错误

### ISSUE THREAD

**Issue by coolit** [fox-one/bugs-hunter#77]
**描述错误**
01- 今早我有2份待领取，我点击其中一份后，该页面变成只显示所有已过期的积分。必须重新进入该页面才会看到另一份待领取。 02- 待领取领完后，为啥只显示所有已过期的积分？

**环境信息（请填写以下信息）：**
  - 操作系统：安卓
  - 版本：最新
  - Fox.ONE 邀请码：85MYMM

**Comment by riririridiculous** [comment]
奖励已发放 可升级到最新版本查看 谢谢！
