### ISSUE TITLE
宝箱通知点进去，提示“This page could not be found”。

### ISSUE THREAD

**Issue by zyh127** [fox-one/bugs-hunter#78]
**描述错误**
宝箱通知点进去，提示“This page could not be found”。

**重现**
重现行为的步骤：
1.打开宝箱，等待出现宝箱领取通知
2.点击宝箱领取通知
3.看到错误页面

**预期行为**
正常应该显示领取了多少、哪些代币。

**环境信息（请填写以下信息）：**
  - 操作系统：安卓
  - 版本8.1.0
  - 设备：荣耀8c
  - 操作系统：EMUI
  - 版本 8.2.0
  - 手机系统语言 [中文]
  - Fox.ONE 版本 2.9.1（198）
  - Fox.ONE 邀请码YWXRMM

**Comment by zyh127** [comment]
![问题截图](https://user-images.githubusercontent.com/29365811/72656450-3567c880-39d6-11ea-9adf-eeefe8ecb07e.jpg)

**Comment by riririridiculous** [comment]
描述不够清晰，宝箱领取通知是指？可否录制视频或截图联系 mixin ID：37160854.
谢谢支持！
