### ISSUE TITLE
最小下单数量

### ISSUE THREAD

**Issue by coolit** [fox-one/bugs-hunter#79]
**描述错误**
xin/usdt交易对，提示的最小下单数量是0.0001，而实际上0.001个xin时就无法下单了。

**环境信息（请填写以下信息）：**
  - 操作系统：安卓
  - 版本：最新
  - Fox.ONE 邀请码：85MYMM

**Comment by riririridiculous** [comment]
新年快乐！已知问题且已修复，建议下次提 bug 时请配图，感谢支持。
