### ISSUE TITLE
一次性收过很多验证短信

### ISSUE THREAD

**Issue by lanvige** [fox-one/bugs-hunter#8]
**描述错误**
在我注册产品成为用户时，一次性的收到了很多验证码短信。

**重现**
重现行为的步骤：
下载 APP
点击注册
输入手机号码

**预期行为**
在最快的时间发送一次短信。

**截图**
![-w400](https://user-images.githubusercontent.com/175512/68558078-f4ea4c80-0472-11ea-8f05-fda27f7964a9.jpeg)

**环境信息（请填写以下信息）：**
  - 操作系统：iOS
  - 设备：iPhone X
  - 操作系统：[例如 iOS 8.1]
  - 版本 [例如 22]
  - Fox.ONE 版本 2.7.0
  - Fox.ONE 邀请码 DRMVKP

**Comment by cw35** [comment]
以下是telesign的回复:

```我们后台查到这个用户只有一条交易记录。多条信息有可能是当时用户处于信号不好的位置，我们的信息发送成功到用户但是并未到达运营商，所以出发运营商重复发送的响应机制。这只是一个单个用户的暂时性问题。```

暂时定性成偶发事件，持续关注着的。
