### ISSUE TITLE
苹果手机 6 P 资产转账到 Mixin Messenger时，出现bug

### ISSUE THREAD

**Issue by guofucheng1229** [fox-one/bugs-hunter#81]
**苹果手机资产转账bug**
  苹果6，转XIN Token到 Mixin Messager 时，转账资产自动更改成 首页排名第一的资产，需要手动改回，再转账。

**重现**

1.点击 “资产估值”，进入；
2.点击“XIN”资产标识；
3.点“转出”
4.点“转出到Mixin Messenger” 
5.出现错误 ： 资产自动默认为 FMC1 （我的资产排行 FMC1 排第一位）
 需要手动更改为 XIN ，才能继续。

**预期行为**
转账资产自动识别

**环境信息（请填写以下信息）：**
  - 操作系统：[ iOS]
  - 浏览器 [  ]
  - 版本 [例如 22]
  - 设备：[iPhone 6P]
  - 操作系统：[iOS 12.4]
  - 版本 [格式化后]
  - 手机系统语言 [中文]
  - Fox.ONE 版本 [最新]

**Comment by riririridiculous** [comment]
问题进一步确认中，待问题确认完毕后发放奖励。新年快乐，感谢支持！
