### ISSUE TITLE
钱包中bcat的价格显示不正确

### ISSUE THREAD

**Issue by zyh127** [fox-one/bugs-hunter#82]
描述错误
钱包中bcat的价格显示不正确。

重现
重现行为的步骤：
1.点击钱包
2.点击资产
3.查看bcat的价格

环境信息（请填写以下信息）：

    操作系统：安卓
    版本8.1.0
    设备：荣耀8c
    操作系统：EMUI
    版本 8.2.0
    手机系统语言 [中文]
    Fox.ONE 版本 2.9.1（198）
    Fox.ONE 邀请码YWXRMM

截图
![Screenshot_20200120-114608](https://user-images.githubusercontent.com/29365811/72697752-fecbb280-3b7b-11ea-9b56-01e2d37a940a.jpg)

**Comment by zyh127** [comment]
![Screenshot_20200120-114608](https://user-images.githubusercontent.com/29365811/72697791-363a5f00-3b7c-11ea-8724-3708db4721c0.jpg)

**Comment by zyh127** [comment]
![Screenshot_20200120-114619](https://user-images.githubusercontent.com/29365811/72697915-bcef3c00-3b7c-11ea-9f03-df1bade16f30.jpg)

**Comment by riririridiculous** [comment]
已知问题，后端取价格逻辑需要优化。新年快乐，感谢支持。
