### ISSUE TITLE
小钱包读取不到转账记录

### ISSUE THREAD

**Issue by kyokokiss** [fox-one/bugs-hunter#84]
近期小钱包增加了 SNAPSHOTS:READ 权限，但是在增加这个权限之前的用户，打开小钱包没有要求用户重新授权，导致老用户无法查看转账记录，需要手动取消权限、再重新授权才可以。老用户使用小钱包可能会误以为小钱包有问题，请改进一下，谢谢。

**Comment by riririridiculous** [comment]
问题已解决，请提供邀请码以便我们给予您发放奖励。新年快乐，感谢反馈！
