### ISSUE TITLE
CAN'T BUY MEMBERSHIP WITH CRYPTO ERROR

### ISSUE THREAD

**Issue by fithozee** [fox-one/bugs-hunter#85]
**Describe the bug**
CAN'T BUY MEMBERSHIP WITH CRYPTO ERROR
**To Reproduce**
1. Go to MEMBERSHIP
2. BUY WITH CRYPTO
3. I USE BTC

![Screenshot_2020-01-21-20-07-26-823_com fox one](https://user-images.githubusercontent.com/57563502/72809202-c3b9a400-3c8d-11ea-8a84-2030b8423c3b.png)

**Information:**
 - OS: ANDROID 9

 - Phone Device: XIAOMI MI9T PRO
 - Phone OS: MIUI
 - Phone Version [e.g. 22]
 - Phone Language [INDONESIA]
 - Fox.ONE Version [e.g. 2.10]
 - Fox.ONE Referral Code 479RZK

**Additional context**

**Comment by riririridiculous** [comment]
The problem has been confirmed and the reward will be distributed within a week. 
Thank you for your support. Happy New year!

**Comment by riririridiculous** [comment]
fixed. update to the latest version 😊
