### ISSUE TITLE
WRONG LETTER ON WRONG PIN

### ISSUE THREAD

**Issue by fithozee** [fox-one/bugs-hunter#86]
**Describe the bug**
I TYPE WRONG PIN ON THE PAYMENT AND SEE THE SCREENSHOT

**To Reproduce**
1. Go to BUY MEMBERSHIP WITH CRYPTO
2. I CHOOSE BTC
3. See error

**Expected behavior**
THE CORRECT LETTER IS THE PIN IS WRONG

**Screenshots**
![Screenshot_2020-01-21-20-13-03-574_com fox one](https://user-images.githubusercontent.com/57563502/72809644-9c170b80-3c8e-11ea-8301-80eac3b2d207.png)

**Information:**
 - OS: ANDROID 9

 - Phone Device: XIAOMI MI9T PRO
 - Phone OS: MIUI
 - Phone Version [e.g. 22]
 - Phone Language [INDONESIA]
 - Fox.ONE Version [e.g. 2.10]
 - Fox.ONE Referral Code 479RZK

**Additional context**

**Comment by riririridiculous** [comment]
The problem has been confirmed and the reward will be distributed within a week.
Thank you for your support. Happy New year!

**Comment by zhdhr0000** [comment]
it will be fixed at version 2.11.1
