### ISSUE TITLE
WRONG MINIMUM AMOUNT OF TRADE ETH/BTC

### ISSUE THREAD

**Issue by fithozee** [fox-one/bugs-hunter#88]
**Describe the bug**
A WRONG MINIMUM AMOUNT OF TRADE ON ETH/BTC
**To Reproduce**
1. Go to TRADE ETH/BTC
2. IT'S SHOW THAT MINIMUM IS 0.0001 BTC , BUT I CAN'T TRADE WITH THAT AMOUNT. THE CORRECT IS 0.001 BTC

**Screenshots**
![Screenshot_2020-01-22-22-07-17-268_com fox one](https://user-images.githubusercontent.com/57563502/72938730-11bdcd00-3d9e-11ea-8a26-9c74513cea32.png)

**Information:**
Information:

OS: ANDROID 9

Phone Device: XIAOMI MI9T PRO

Phone OS: MIUI

Phone Version [e.g. 22]

Phone Language [INDONESIA]

Fox.ONE Version [e.g. 2.10]

Fox.ONE Referral Code 479RZK

Additional context

**Comment by riririridiculous** [comment]
The problem has been confirmed and the reward will be distributed within a week.
Thank you for your support. Happy New year!

**Comment by riririridiculous** [comment]
fixed. update to the latest version
