### ISSUE TITLE
WRONG MINIMUM AMOUNT OF TRADE ON XIN/USDT

### ISSUE THREAD

**Issue by fithozee** [fox-one/bugs-hunter#89]
Describe the bug
A WRONG MINIMUM AMOUNT OF TRADE ON XIN/USDT
To Reproduce

Go to TRADE XIN/USDT
IT'S SHOW THAT MINIMUM IS 0.0001 XIN
N, BUT I CAN'T TRADE WITH THAT AMOUNT. THE CORRECT IS 0.01 XIN
See error

**Expected behavior**

**Screenshots**
![Screenshot_2020-01-23-05-11-00-992_com fox one](https://user-images.githubusercontent.com/57563502/72939211-0a4af380-3d9f-11ea-8b90-a4edfb79aa10.png)

OS: ANDROID 9

Phone Device: XIAOMI MI9T PRO

Phone OS: MIUI

Phone Version [e.g. 22]

Phone Language [INDONESIA]

Fox.ONE Version [e.g. 2.10]

Fox.ONE Referral Code 479RZK

Additional context

**Comment by riririridiculous** [comment]
similar to #88
