### ISSUE TITLE
交易对中缺少分隔符（/）

### ISSUE THREAD

**Issue by shen-huang** [fox-one/bugs-hunter#91]
**描述错误**
B.Watch DEX 交易对名称中缺少分隔符（/）

**重现**
重现行为的步骤：
1. 转到“交易”分页
2. 点击“汉堡包图标（☰）”
3. 任选某一交易对
4. 看到错误

**预期行为**
标题中显示的交易对应该有分隔符（/），如“BOXUSDT”应为“BOX/USDT”

**截图**
![B_Watch_DEX_缺少分隔符](https://raw.githubusercontent.com/shen-huang/img/master/2020-01/B_Watch_DEX_missing_solidus.jpeg)

**环境信息（请填写以下信息）：**
  - 操作系统：Android 9
  - 浏览器：Mixin Messenger 内置浏览器
  - 版本：Mixin Messenger 0.18.10
  - 设备：三星 Note 9
  - 手机系统语言：中文
  - B.Watch DEX 版本：内测，暂未找到版本显示
  - Fox.ONE 邀请码：37ZRVZ

**Comment by riririridiculous** [comment]
已经修复，谢谢反馈！奖励将在 1 周内发放。
