### ISSUE TITLE
显示的人民币价格有误

### ISSUE THREAD

**Issue by zyh127** [fox-one/bugs-hunter#92]
**描述错误**
显示的人民币价格有误

**重现**
重现行为的步骤：
1.点击“ 三个横杠”
2.点击“设置”
3.点击“首选货币”
4.点击“人民币”
5.返回首页
6.点击“USDT”
7.看到“box/USDT交易对”显示的价格有误。

**预期行为**
应该显示正确的价格。

**截图**
![Screenshot_20200125-131320](https://user-images.githubusercontent.com/29365811/73116649-b3971280-3f74-11ea-983e-efa20ba39102.jpg)

**环境信息（请填写以下信息）：**
  - 操作系统：[安卓]
  - 版本 [8.1.0]
  - 设备：[荣耀8C]
  - 操作系统：[EMUI]
  - 版本 [8.2.0]
  - 手机系统语言 [中文]
  -  版本 [内测]
  - Fox.ONE 邀请码 [YWXRMM]

**Comment by divisey** [comment]
fixed

**Comment by riririridiculous** [comment]
已修复，谢谢反馈！奖励将在 1 周内发放
