### ISSUE TITLE
语言英语开关无效

### ISSUE THREAD

**Issue by zyh127** [fox-one/bugs-hunter#93]
**描述错误**
语言英语开关无效

**重现**
重现行为的步骤：
1.点击“三个横”
2.点击“设置”
3.点击“语言”
4.选择“英文”
5.选择“好的”
6.看到错误

**预期行为**
变成英文。

**截图**
![Screenshot_20200125-134837](https://user-images.githubusercontent.com/29365811/73116935-a4ff2a00-3f79-11ea-8517-2f93ac2d1e3c.jpg)

**环境信息（请填写以下信息）：**
  - 操作系统：[安卓]
  - 版本 [8.1.0]
  - 设备：[荣耀8C]
  - 操作系统：[EMUI]
  - 版本 [8.2.0]
  - 手机系统语言 [中文]
  -  版本 [内测]
  - Fox.ONE 邀请码 [YWXRMM]

**Comment by riririridiculous** [comment]
已经修复，隐藏了该设置，现语言设置跟随手机系统语言。谢谢反馈！奖励将在 1 周内发放。
