### ISSUE TITLE
[bwatch dex]下单＆撤单余额不会更新问题

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#94]
**描述错误**
交易时提交订单后，页面显示的余额还是下单前的数字。下拉页面刷新数字不会变化。撤单情况一样。

**重现**
重现行为的步骤：
1.转到“ 市场“
2.点击“ BTCUSDT交易对”
3.点击“ 买入”
4.看到显示余额：30usdt
5.输入价格，数量，点击买入btc
6.付款8usdt
7.付款成功，返回交易页面
8.看到错误：余额显示30usdt
9.下拉刷新，无变化
10. 退出该交易对重新进入，余额依旧显示30usdt
11. 撤单情况一样，余额不会更新
**预期行为**
8.9.10显示22usdt

**截图**
![第4步](https://wx3.sinaimg.cn/large/007nqC8Ygy1gb8t5otgfpj30ku112jzb.jpg)
第4步：刚进入交易页面的显示情况

![第6步](https://wx1.sinaimg.cn/large/007nqC8Ygy1gb8t6rfkquj30ku1127c5.jpg)
第6步：付款8u

![第8步](https://wx4.sinaimg.cn/large/007nqC8Ygy1gb8t5pg8l8j30ku112qbp.jpg)
第8步：下单成功后余额显示30usdt

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
-mixin 版本：[完整版0.19.0（270)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
无

**Comment by divisey** [comment]
fixed

**Comment by riririridiculous** [comment]
已经修复，谢谢反馈！奖励将在 1 周内发放。
