### ISSUE TITLE
[bwatch dex]撤单相关问题 

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#95]
**描述错误**
点击撤销订单，页面不会出现提示，并且依然显示该订单。但退出重进却发现订单已经撤销。

**重现**
重现行为的步骤：
1.转到“ 市场“
2.点击“ BTCUSDT交易对”
3.点击“ 买入”
4.输入价格，数量，点击买入btc
5.付款成功
6.下滑看到已提交订单
7.点击撤销订单
8.看到错误：该订单依旧显示在页面上
9.点击左上角返回键，重新点击“买入”，发现页面已不显示该订单

**预期行为**
第8步 订单信息从页面消失

**截图**

![第7步](https://wx3.sinaimg.cn/mw690/007nqC8Ygy1gba1na3yymj30ku112n25.jpg)
第7，8步：点击撤销订单， 该订单依旧显示在页面上

![第9步](https://wx4.sinaimg.cn/mw690/007nqC8Ygy1gba1navts6j30ku112goo.jpg)
第9步：退出重进发现订单已消失

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
- mixin 版本：[完整版0.19.0（270)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
无

**Comment by divisey** [comment]
fixed

**Comment by riririridiculous** [comment]
该问题同 #94 WebSocket 自动更新。
