### ISSUE TITLE
[bwatch dex]提交订单后订单簿不会更新问题 

### ISSUE THREAD

**Issue by lilasxie** [fox-one/bugs-hunter#96]
**描述错误**
提交买单或卖单后，发现订单簿并未将该订单信息同步上去。

**重现**
重现行为的步骤：
1.转到“ 市场“
2.点击“ BTCUSDT交易对”
3.点击“ 买入”
4.输入价格 8000 ，数量 0.001 ，点击 “买入btc” 按钮
5.付款成功
6.看到错误：订单簿上面并未显示价格为8000的订单

**预期行为**
6 看到订单簿上面出现价格为 8000， 数量为 0.001 的买入订单

**截图**
![第4步](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gba1n99fp7j30ku112tde.jpg)
第4步：下单

![第6步](https://wx1.sinaimg.cn/mw690/007nqC8Ygy1gba1n89mj4j30ku11247r.jpg)
第6步：订单簿上面并未显示价格为8000的订单

**环境信息（请填写以下信息）：**

- 操作系统：[ iOS ]
- 设备：[ iPhone 7]
- 操作系统：[iOS 11.4.1]
-mixin 版本：[完整版0.19.0（270)]
- Fox.ONE 邀请码 [DNR42M]

**其他内容**
无

**Comment by divisey** [comment]
fixed

**Comment by riririridiculous** [comment]
该问题同 #94 WebSocket 自动更新。
