### ISSUE TITLE
登陆后MINXI账户余额变动，显示不正确

### ISSUE THREAD

**Issue by ytpc88** [fox-one/bugs-hunter#97]
电脑网页端登陆后，发现余额不足以交易 ，我在MINXI帐户中充值了USDT。但交易端显示还是余额不足。重新登陆还是不行，最后才发现是BTC网络的USDT，这个版本的不支持。

**Comment by riririridiculous** [comment]
仅支持 ERC20 版本的 USDT.

可以阅读以下链接，找到合适的方法切换 USDT 版本
https://fox.zendesk.com/hc/zh-cn/articles/360031509932
