### ISSUE TITLE
价格信息显示不正确

### ISSUE THREAD

**Issue by ytpc88** [fox-one/bugs-hunter#98]
BOX 的价格显示不正确。我已经按1.58USDT成交 页面上显示还是1.55USDT 。
![微信图片_20200127203235](https://user-images.githubusercontent.com/60347297/73175103-610c5080-4144-11ea-8f41-2ca90338ec73.png)

**Comment by divisey** [comment]
fixed

**Comment by riririridiculous** [comment]
该问题同 #94 WebSocket 自动更新。谢谢反馈，下次提问请记得按照模版具体描述哈，一定要填写 Foxone 邀请码哦！不然找不到你哈！
