### ISSUE TITLE
余额不正确导致不能连续购买

### ISSUE THREAD

**Issue by ytpc88** [fox-one/bugs-hunter#99]
如果我成交了一笔订单，比如我以1.58U的价格成交了０.１个BOX。但是我在Ｂ.ＷＡＴＣＨ交易界面里的余额并不会减少。导致下一笔交易由于显示不正确导致交易余额不足。

**Comment by riririridiculous** [comment]
该问题同 #94 ，感谢反馈！我们会尽快修复
